// qdiiTagMap.ts
// Auto-generated tag map for QDII fund holdings
// Keys = holding_name_std from the holdings database
// Tags: 地域 (geography), 主题 (investment theme), 债券 (bond type)
//
// Next.js QD 基金池筛选（tag_taxonomy 维度映射）见 mf-holdings-dashboard/src/data/qdiiFundFilterConfig.ts

export type HoldingTag = {
  地域?: "中国大陆" | "中国香港" | "中国台湾" | "日本" | "韩国" | "印度" | "新加坡" | "其他";
  主题?: ("HALO" | "高股息" | "科技" | "AI硬件" | "AI软件")[];
  债券?: "投资级别债" | "垃圾债" | "亚洲债" | "新兴市场债";
};

export const qdiiHoldingTags: Record<string, HoldingTag> = {

  // ══════════════════════════════════════════════
  // EQUITIES — AI硬件
  // ══════════════════════════════════════════════
  "NVIDIA CORP": { 地域: "其他", 主题: ["AI硬件"] },
  "NVIDIA Corp.": { 地域: "其他", 主题: ["AI硬件"] },
  "NVIDIA Corp": { 地域: "其他", 主题: ["AI硬件"] },
  "Nvidia": { 地域: "其他", 主题: ["AI硬件"] },
  "英伟达": { 地域: "其他", 主题: ["AI硬件"] },
  "BROADCOM INC": { 地域: "其他", 主题: ["AI硬件"] },
  "Broadcom": { 地域: "其他", 主题: ["AI硬件"] },
  "Broadcom, Inc.": { 地域: "其他", 主题: ["AI硬件"] },
  "Broadcom Inc": { 地域: "其他", 主题: ["AI硬件"] },
  "博通": { 地域: "其他", 主题: ["AI硬件"] },
  "ADVANCED MICRO DEVICES": { 地域: "其他", 主题: ["AI硬件"] },
  "APPLIED MATERIAL INC": { 地域: "其他", 主题: ["AI硬件"] },
  "LAM RESEARCH CORP": { 地域: "其他", 主题: ["AI硬件"] },
  "泛林集团": { 地域: "其他", 主题: ["AI硬件"] },
  "MICRON TECHNOLOGY INC": { 地域: "其他", 主题: ["AI硬件"] },
  "美光科技": { 地域: "其他", 主题: ["AI硬件"] },
  "TEXAS INSTRUMENTS INC": { 地域: "其他", 主题: ["AI硬件"] },
  "Texas Instruments": { 地域: "其他", 主题: ["AI硬件"] },
  "ASML HOLDING NV": { 地域: "其他", 主题: ["AI硬件"] },
  "ASML Holding NV": { 地域: "其他", 主题: ["AI硬件"] },
  "ASML Holding": { 地域: "其他", 主题: ["AI硬件"] },
  "ASML": { 地域: "其他", 主题: ["AI硬件"] },
  "阿斯麦": { 地域: "其他", 主题: ["AI硬件"] },
  "AMPHENOL CORP-CL A": { 地域: "其他", 主题: ["AI硬件"] },
  "AMPHENOL CORP": { 地域: "其他", 主题: ["AI硬件"] },
  "AMPHENOL CORP-CL A (美国)": { 地域: "其他", 主题: ["AI硬件"] },
  "VERTIV HOLDINGS CO A": { 地域: "其他", 主题: ["AI硬件"] },
  "Veritiv Holdings Co": { 地域: "其他", 主题: ["AI硬件"] },
  "COHERENT CORP (美国)": { 地域: "其他", 主题: ["AI硬件"] },
  "CORNING INC (美国)": { 地域: "其他", 主题: ["AI硬件"] },
  "Marvell Technology Inc.": { 地域: "其他", 主题: ["AI硬件"] },
  "MONOLITHIC POWER SYSTEMS INC (美国)": { 地域: "其他", 主题: ["AI硬件"] },
  "KEYSIGHT TECHNOLOGIES IN (美国)": { 地域: "其他", 主题: ["AI硬件"] },
  "CoreWeave 'A'": { 地域: "其他", 主题: ["AI硬件"] },
  "Credo Technology": { 地域: "其他", 主题: ["AI硬件"] },
  "FormFactor": { 地域: "其他", 主题: ["AI硬件"] },
  "FLEX LTD": { 地域: "其他", 主题: ["AI硬件"] },
  "SANDISK CORP": { 地域: "其他", 主题: ["AI硬件"] },
  "TE Connectivity PLC": { 地域: "其他", 主题: ["AI硬件"] },
  "泰科电子": { 地域: "其他", 主题: ["AI硬件"] },
  "恩智浦半导体": { 地域: "其他", 主题: ["AI硬件"] },
  "爱德万测试": { 地域: "日本", 主题: ["AI硬件"] },

  // Taiwan AI硬件
  "Taiwan Semiconductor Manufacturing": { 地域: "中国台湾", 主题: ["AI硬件", "高股息"] },
  "TAIWAN SEMICONDUCTOR MFG CO LTD": { 地域: "中国台湾", 主题: ["AI硬件", "高股息"] },
  "TAIWAN SEMICONDUCTOR MANUFACTURING CO LTD": { 地域: "中国台湾", 主题: ["AI硬件", "高股息"] },
  "TAIWAN SEMICONDUCTOR-SP ADR": { 地域: "中国台湾", 主题: ["AI硬件", "高股息"] },
  "TAWAN SEMICONDUCTOR-SP ADR": { 地域: "中国台湾", 主题: ["AI硬件", "高股息"] },
  "Taiwan Semiconductor Manufacturing Company": { 地域: "中国台湾", 主题: ["AI硬件", "高股息"] },
  "Taiwan Semiconductor": { 地域: "中国台湾", 主题: ["AI硬件", "高股息"] },
  "台积电": { 地域: "中国台湾", 主题: ["AI硬件", "高股息"] },
  "TSMC": { 地域: "中国台湾", 主题: ["AI硬件", "高股息"] },
  "MEDIATEK INC": { 地域: "中国台湾", 主题: ["AI硬件"] },
  "ASE Technology Holding": { 地域: "中国台湾", 主题: ["AI硬件"] },
  "Compeq Manufacturing": { 地域: "中国台湾", 主题: ["AI硬件"] },
  "UNIMICRON TECHNOLOGY CORP": { 地域: "中国台湾", 主题: ["AI硬件"] },
  "King Yuan Electronics": { 地域: "中国台湾", 主题: ["AI硬件"] },
  "Lite-On Technology": { 地域: "中国台湾", 主题: ["AI硬件"] },
  "WIWYNN CORPORATION CORP": { 地域: "中国台湾", 主题: ["AI硬件"] },
  "Elite Material": { 地域: "中国台湾", 主题: ["AI硬件"] },
  "Delta Electronics, Inc.": { 地域: "中国台湾", 主题: ["AI硬件", "科技"] },
  "Delta Electronics": { 地域: "中国台湾", 主题: ["AI硬件", "科技"] },
  "FORMOSA PLASTICS CORP": { 地域: "中国台湾" },
  "Uni-President Enterprises Corp.": { 地域: "中国台湾" },

  // Korea AI硬件
  "SAMSUNG ELECTRONICS CO LTD": { 地域: "韩国", 主题: ["AI硬件", "高股息"] },
  "Samsung Electronics": { 地域: "韩国", 主题: ["AI硬件", "高股息"] },
  "SAMSUNG ELECTRONICS LTD": { 地域: "韩国", 主题: ["AI硬件", "高股息"] },
  "SAMSUNG ELECTRONICS GDS REPRESENT": { 地域: "韩国", 主题: ["AI硬件", "高股息"] },
  "三星电子": { 地域: "韩国", 主题: ["AI硬件", "高股息"] },
  "三星": { 地域: "韩国", 主题: ["AI硬件", "高股息"] },
  "SK HYNIX INC": { 地域: "韩国", 主题: ["AI硬件"] },
  "SK hynix": { 地域: "韩国", 主题: ["AI硬件"] },
  "SK hynix, Inc.": { 地域: "韩国", 主题: ["AI硬件"] },
  "SK Hynix, Inc.": { 地域: "韩国", 主题: ["AI硬件"] },
  "SK海力士": { 地域: "韩国", 主题: ["AI硬件"] },
  "SAMSUNG ELECTRO-MECHANICS CO LTD": { 地域: "韩国", 主题: ["AI硬件"] },
  "WONIK MATERIALS CO LTD": { 地域: "韩国", 主题: ["AI硬件"] },
  "ISUPTASYS CO LTD": { 地域: "韩国", 主题: ["AI硬件"] },

  // Japan AI硬件
  "HOYA": { 地域: "日本", 主题: ["AI硬件", "科技"] },
  "Hoya Corp": { 地域: "日本", 主题: ["AI硬件", "科技"] },
  "HITACHI LTD (日本)": { 地域: "日本", 主题: ["AI硬件", "科技"] },
  "Hitachi Ltd": { 地域: "日本", 主题: ["AI硬件", "科技"] },
  "TOYO TANSO CO LTD": { 地域: "日本", 主题: ["AI硬件"] },
  "Mitsubishi Electric Corp": { 地域: "日本", 主题: ["AI硬件", "科技"] },
  "INFINEON TECHNOLOGIES AG": { 地域: "其他", 主题: ["AI硬件"] },
  "HD HYUNDAI ELECTRIC CO LTD": { 地域: "韩国", 主题: ["AI硬件"] },
  "DOOSAN ENERBILTY CO LTD": { 地域: "韩国", 主题: ["科技"] },

  // ══════════════════════════════════════════════
  // EQUITIES — AI软件
  // ══════════════════════════════════════════════
  "MICROSOFT CORP": { 地域: "其他", 主题: ["AI软件", "高股息"] },
  "Microsoft": { 地域: "其他", 主题: ["AI软件", "高股息"] },
  "Microsoft Corp.": { 地域: "其他", 主题: ["AI软件", "高股息"] },
  "微软": { 地域: "其他", 主题: ["AI软件", "高股息"] },
  "ALPHABET INC": { 地域: "其他", 主题: ["AI软件", "科技"] },
  "ALPHABET INC-CL A": { 地域: "其他", 主题: ["AI软件", "科技"] },
  "ALPHABET INC CLASS A": { 地域: "其他", 主题: ["AI软件", "科技"] },
  "ALPHABET INC CL A": { 地域: "其他", 主题: ["AI软件", "科技"] },
  "Alphabet": { 地域: "其他", 主题: ["AI软件", "科技"] },
  "Alphabet, Inc.": { 地域: "其他", 主题: ["AI软件", "科技"] },
  "Alphabet Inc": { 地域: "其他", 主题: ["AI软件", "科技"] },
  "Alphabet Inc.": { 地域: "其他", 主题: ["AI软件", "科技"] },
  "Alphabet Inc. Class A": { 地域: "其他", 主题: ["AI软件", "科技"] },
  "ALPHABET(谷歌母公司)": { 地域: "其他", 主题: ["AI软件", "科技"] },
  "AMAZON.COM INC": { 地域: "其他", 主题: ["AI软件", "科技"] },
  "AMAZON COM INC": { 地域: "其他", 主题: ["AI软件", "科技"] },
  "Amazon.com, Inc.": { 地域: "其他", 主题: ["AI软件", "科技"] },
  "Amazon.com": { 地域: "其他", 主题: ["AI软件", "科技"] },
  "Amazon.Com": { 地域: "其他", 主题: ["AI软件", "科技"] },
  "Amazon": { 地域: "其他", 主题: ["AI软件", "科技"] },
  "亚马逊": { 地域: "其他", 主题: ["AI软件", "科技"] },
  "META PLATFORMS INC": { 地域: "其他", 主题: ["AI软件", "科技"] },
  "META PLATFORMS INC CLASS A": { 地域: "其他", 主题: ["AI软件", "科技"] },
  "META PLATFORMS INC-CLASS A": { 地域: "其他", 主题: ["AI软件", "科技"] },
  "Meta Platforms": { 地域: "其他", 主题: ["AI软件", "科技"] },
  "Meta Platforms 'A'": { 地域: "其他", 主题: ["AI软件", "科技"] },
  "Meta Platforms, Inc.": { 地域: "其他", 主题: ["AI软件", "科技"] },
  "Meta(脸书母公司)": { 地域: "其他", 主题: ["AI软件", "科技"] },
  "ORACLE CORP": { 地域: "其他", 主题: ["AI软件"] },
  "Oracle": { 地域: "其他", 主题: ["AI软件"] },
  "SAP SE": { 地域: "其他", 主题: ["AI软件"] },
  "AppLovin 'A'": { 地域: "其他", 主题: ["AI软件"] },
  "AppLovin Corp": { 地域: "其他", 主题: ["AI软件"] },
  "Snowflake": { 地域: "其他", 主题: ["AI软件"] },
  "Crowdstrike Holdings Inc": { 地域: "其他", 主题: ["AI软件"] },
  "AUTODESK": { 地域: "其他", 主题: ["AI软件"] },
  "Autodesk Inc": { 地域: "其他", 主题: ["AI软件"] },
  "GARTNER INC": { 地域: "其他", 主题: ["AI软件"] },
  "Nebius": { 地域: "其他", 主题: ["AI软件"] },
  "TENCENT HOLDINGS LTD": { 地域: "中国香港", 主题: ["AI软件", "高股息"] },
  "Tencent Holdings": { 地域: "中国香港", 主题: ["AI软件", "高股息"] },
  "Tencent Holdings Ltd.": { 地域: "中国香港", 主题: ["AI软件", "高股息"] },
  "Tencent Holdings Ltd": { 地域: "中国香港", 主题: ["AI软件", "高股息"] },
  "TENCENT HLDGS LTD": { 地域: "中国香港", 主题: ["AI软件", "高股息"] },
  "Tencent": { 地域: "中国香港", 主题: ["AI软件", "高股息"] },
  "腾讯": { 地域: "中国香港", 主题: ["AI软件", "高股息"] },
  "ALIBABA GROUP HOLDING LTD": { 地域: "中国香港", 主题: ["AI软件", "科技"] },
  "ALIBABA GROUP HOLDING ADR REPRESENTATIVE": { 地域: "中国香港", 主题: ["AI软件", "科技"] },
  "Alibaba Group Holding": { 地域: "中国香港", 主题: ["AI软件", "科技"] },
  "Alibaba Group Holding Limited": { 地域: "中国香港", 主题: ["AI软件", "科技"] },
  "Alibaba": { 地域: "中国香港", 主题: ["AI软件", "科技"] },
  "阿里巴巴": { 地域: "中国香港", 主题: ["AI软件", "科技"] },
  "阿里巴巴集团": { 地域: "中国香港", 主题: ["AI软件", "科技"] },
  "BAIDU INC": { 地域: "中国大陆", 主题: ["AI软件"] },
  "百度": { 地域: "中国大陆", 主题: ["AI软件"] },
  "NETEASE INC": { 地域: "中国大陆", 主题: ["AI软件"] },
  "NetEase": { 地域: "中国大陆", 主题: ["AI软件"] },
  "NetEase Inc": { 地域: "中国大陆", 主题: ["AI软件"] },
  "网易": { 地域: "中国大陆", 主题: ["AI软件"] },

  // ══════════════════════════════════════════════
  // EQUITIES — 科技 (general tech, not AI-specific)
  // ══════════════════════════════════════════════
  "APPLE INC": { 地域: "其他", 主题: ["科技", "高股息"] },
  "Apple, Inc.": { 地域: "其他", 主题: ["科技", "高股息"] },
  "Apple Inc.": { 地域: "其他", 主题: ["科技", "高股息"] },
  "Apple": { 地域: "其他", 主题: ["科技", "高股息"] },
  "苹果": { 地域: "其他", 主题: ["科技", "高股息"] },
  "TESLA INC": { 地域: "其他", 主题: ["科技"] },
  "Tesla": { 地域: "其他", 主题: ["科技"] },
  "ACCENTURE PLC": { 地域: "其他", 主题: ["科技"] },
  "COGNIZANT TECH SOLUTIONS CORP": { 地域: "其他", 主题: ["科技"] },
  "INFOSYS LTD": { 地域: "印度", 主题: ["科技"] },
  "Infosys Ltd.": { 地域: "印度", 主题: ["科技"] },
  "HCL TECHNOLOGIES LTD": { 地域: "印度", 主题: ["科技"] },
  "SIEMENS AG": { 地域: "其他", 主题: ["科技"] },
  "Siemens AG": { 地域: "其他", 主题: ["科技"] },
  "西门子": { 地域: "其他", 主题: ["科技"] },
  "ERICSSON": { 地域: "其他", 主题: ["科技"] },
  "ABB LTD": { 地域: "其他", 主题: ["科技"] },
  "ABB LTD-REG": { 地域: "其他", 主题: ["科技"] },
  "Sea ADR": { 地域: "新加坡", 主题: ["科技"] },
  "Shopify 'A'": { 地域: "其他", 主题: ["科技"] },
  "Netflix, Inc.": { 地域: "其他", 主题: ["科技"] },
  "DoorDash 'A'": { 地域: "其他", 主题: ["科技"] },
  "Robinhood Markets": { 地域: "其他", 主题: ["科技"] },
  "Robinhood Markets Inc": { 地域: "其他", 主题: ["科技"] },
  "BLOCK INC": { 地域: "其他", 主题: ["科技"] },
  "CIENA CORPORATION": { 地域: "其他", 主题: ["科技"] },
  "Analog Devices": { 地域: "其他", 主题: ["科技"] },
  "SONY": { 地域: "日本", 主题: ["科技", "高股息"] },
  "Sony Group Corp": { 地域: "日本", 主题: ["科技", "高股息"] },
  "NINTENDO": { 地域: "日本", 主题: ["科技"] },
  "Nintendo": { 地域: "日本", 主题: ["科技"] },
  "FAST RETAILING": { 地域: "日本", 主题: ["高股息"] },
  "SAMSUNG C&T CORP": { 地域: "韩国" },
  "SK SQUARE CO LTD": { 地域: "韩国", 主题: ["科技"] },
  "SK SQUARE LTD": { 地域: "韩国", 主题: ["科技"] },
  "ITOCHU Corp": { 地域: "日本", 主题: ["高股息"] },
  "KDDI Corp": { 地域: "日本", 主题: ["高股息"] },
  "Panasonic Holdings Corp": { 地域: "日本" },
  "Tokio Marine Holdings Inc": { 地域: "日本", 主题: ["高股息"] },
  "Sumitomo Mitsui Trust Group Inc": { 地域: "日本", 主题: ["高股息"] },
  "Mitsubishi UFJ Financial Group Inc": { 地域: "日本", 主题: ["高股息"] },
  "MITSUI FUDOSAN CO LTD": { 地域: "日本" },
  "MITSUI FUDOSAN LTD": { 地域: "日本" },
  "FUJIBO HOLDINGS INC": { 地域: "日本" },
  "Dentsu Group Inc": { 地域: "日本" },
  "Suzuki Motor Corp": { 地域: "日本" },
  "ORIX Corp": { 地域: "日本", 主题: ["高股息"] },

  // China Mainland
  "CONTEMPORARY AMPEREX TECHN A": { 地域: "中国大陆", 主题: ["科技"] },
  "CONTEMPORARY AMPEREX TECHNOLOGY CO LTD": { 地域: "中国大陆", 主题: ["科技"] },
  "Contemporary Amperex Technology": { 地域: "中国大陆", 主题: ["科技"] },
  "Contemporary Amperex Technology Co Ltd": { 地域: "中国大陆", 主题: ["科技"] },
  "宁德时代": { 地域: "中国大陆", 主题: ["科技"] },
  "CHINA CONSTRUCTION BANK CORP": { 地域: "中国大陆", 主题: ["高股息"] },
  "China Construction Bank": { 地域: "中国大陆", 主题: ["高股息"] },
  "China Construction Bank Corporation": { 地域: "中国大陆", 主题: ["高股息"] },
  "中国建设银行": { 地域: "中国大陆", 主题: ["高股息"] },
  "CHINA MERCHANTS BANK CO LTD": { 地域: "中国大陆", 主题: ["高股息"] },
  "China Merchants Bank": { 地域: "中国大陆", 主题: ["高股息"] },
  "China Merchants Bank Co., Ltd.": { 地域: "中国大陆", 主题: ["高股息"] },
  "ALUMINUM CORP OF CHINA LTD": { 地域: "中国大陆" },
  "Midea Group": { 地域: "中国大陆", 主题: ["高股息"] },
  "PetroChina Co Ltd": { 地域: "中国大陆", 主题: ["高股息"] },
  "PING AN INSURANCE GROUP CO OF CHINA LTD": { 地域: "中国大陆", 主题: ["高股息"] },
  "Ping An Insurance (Group) Company of China, Ltd.": { 地域: "中国大陆", 主题: ["高股息"] },
  "Ping An Insurance Group": { 地域: "中国大陆", 主题: ["高股息"] },
  "中国平安保险": { 地域: "中国大陆", 主题: ["高股息"] },
  "平安保险": { 地域: "中国大陆", 主题: ["高股息"] },
  "Zijin Mining Group": { 地域: "中国大陆" },
  "Zijin Mining Group Co Ltd": { 地域: "中国大陆" },
  "紫金矿业": { 地域: "中国大陆" },
  "洛阳钼业": { 地域: "中国大陆" },
  "中国宏桥集团": { 地域: "中国大陆" },
  "三一重工": { 地域: "中国大陆" },
  "施耐德电气": { 地域: "其他", 主题: ["科技"] },

  // China HK
  "AIA GROUP LTD": { 地域: "中国香港", 主题: ["高股息"] },
  "AIA Group": { 地域: "中国香港", 主题: ["高股息"] },
  "AIA Group Limited": { 地域: "中国香港", 主题: ["高股息"] },
  "AIA": { 地域: "中国香港", 主题: ["高股息"] },
  "Hong Kong Exchanges & Clearing": { 地域: "中国香港", 主题: ["高股息"] },
  "Hong Kong Exchanges & Clearing Ltd.": { 地域: "中国香港", 主题: ["高股息"] },
  "HKT TRUST AND HKT LTD": { 地域: "中国香港", 主题: ["高股息"] },
  "HSBC": { 地域: "中国香港", 主题: ["高股息"] },
  "HSBC Holdings": { 地域: "中国香港", 主题: ["高股息"] },
  "HSBC Holdings Plc": { 地域: "中国香港", 主题: ["高股息"] },
  "汇丰": { 地域: "中国香港", 主题: ["高股息"] },
  "Standard Chartered": { 地域: "中国香港", 主题: ["高股息"] },
  "渣打银行": { 地域: "中国香港", 主题: ["高股息"] },
  "MEITUAN": { 地域: "中国香港", 主题: ["科技"] },
  "Meituan": { 地域: "中国香港", 主题: ["科技"] },
  "Meituan (Restaurants)": { 地域: "中国香港", 主题: ["科技"] },
  "美团": { 地域: "中国香港", 主题: ["科技"] },
  "XIAOMI CORP": { 地域: "中国香港", 主题: ["科技", "AI硬件"] },
  "Xiaomi Corporation": { 地域: "中国香港", 主题: ["科技", "AI硬件"] },
  "Xiaomi": { 地域: "中国香港", 主题: ["科技", "AI硬件"] },
  "小米": { 地域: "中国香港", 主题: ["科技", "AI硬件"] },
  "PDD HOLDINGS INC": { 地域: "中国香港", 主题: ["科技"] },
  "PDD Holdings": { 地域: "中国香港", 主题: ["科技"] },
  "Trip.com Group": { 地域: "中国香港", 主题: ["科技"] },
  "Trip.com Group Ltd": { 地域: "中国香港", 主题: ["科技"] },
  "Trip.com Group Ltd.": { 地域: "中国香港", 主题: ["科技"] },
  "携程": { 地域: "中国香港", 主题: ["科技"] },
  "TECHTRONIC INDUSTRIES CO LTD": { 地域: "中国香港" },
  "BOC AVIATION LTD": { 地域: "中国香港" },
  "PACIFIC BASIN SHIPPING LTD": { 地域: "中国香港" },
  "DFI RETAIL GROUP HOLDINGS LTD": { 地域: "中国香港" },
  "Link Real Estate Investment Trust": { 地域: "中国香港", 主题: ["HALO"] },
  "Bank of China Ltd.": { 地域: "中国大陆", 主题: ["高股息"] },

  // Singapore
  "DBS": { 地域: "新加坡", 主题: ["高股息"] },
  "DBS GROUP HLDGS LTD": { 地域: "新加坡", 主题: ["高股息"] },
  "Oversea-Chinese Banking": { 地域: "新加坡", 主题: ["高股息"] },
  "SINGAPORE TELECOMMUNICATIONS LTD": { 地域: "新加坡", 主题: ["高股息"] },
  "Capitaland Ascendas REIT": { 地域: "新加坡", 主题: ["HALO"] },
  "Capitaland Integrated Commercial Trust": { 地域: "新加坡", 主题: ["HALO"] },
  "Mapletree Industrial Trust": { 地域: "新加坡", 主题: ["HALO"] },
  "Mapletree Logistics Trust": { 地域: "新加坡", 主题: ["HALO"] },
  "Mapletree Pan Asia Commercial Trust": { 地域: "新加坡", 主题: ["HALO"] },
  "Frasers Centrepoint Trust": { 地域: "新加坡", 主题: ["HALO"] },
  "Keppel DC REIT": { 地域: "新加坡", 主题: ["HALO"] },
  "Suntec Real Estate Investment Trust": { 地域: "新加坡", 主题: ["HALO"] },

  // India
  "HDFC BANK LTD": { 地域: "印度", 主题: ["高股息"] },
  "HDFC Bank": { 地域: "印度", 主题: ["高股息"] },
  "ICICI BANK LTD": { 地域: "印度", 主题: ["高股息"] },
  "ICICI Bank": { 地域: "印度", 主题: ["高股息"] },
  "ICICI Bank Ltd.": { 地域: "印度", 主题: ["高股息"] },
  "BHARTI AIRTEL LTD": { 地域: "印度" },
  "RELIANCE INDUSTRIES LTD": { 地域: "印度", 主题: ["高股息"] },
  "KOTAK MAHINDRA BANK LTD": { 地域: "印度", 主题: ["高股息"] },
  "APOLLO HOSPITALS ENTERPRISE LTD": { 地域: "印度", 主题: ["HALO"] },
  "AXIS BANK LTD": { 地域: "印度", 主题: ["高股息"] },
  "State Bank of India": { 地域: "印度", 主题: ["高股息"] },
  "FORTIS HEALTHCARE INDIA LTD": { 地域: "印度", 主题: ["HALO"] },
  "Power Grid Corporation of India Ltd.": { 地域: "印度", 主题: ["高股息"] },
  "Embassy Office Parks REIT": { 地域: "印度", 主题: ["HALO"] },
  "EMBASSY OFFICE PARKS REIT": { 地域: "印度", 主题: ["HALO"] },
  "HINDALCO INDUSTRIES LTD": { 地域: "印度" },
  "UPL LTD": { 地域: "印度" },

  // ══════════════════════════════════════════════
  // EQUITIES — 高股息 (Europe/US blue chips)
  // ══════════════════════════════════════════════
  "JOHNSON & JOHNSON": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "Johnson & Johnson": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "强生公司": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "ELI LILLY & CO": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "Eli Lilly & Co.": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "Eli Lilly & Co": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "礼来": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "ROCHE HOLDING AG": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "Roche Holding AG": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "Roche": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "罗氏": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "罗氏大药厂": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "NOVARTIS AG": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "Novartis": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "Novartis AG": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "诺华": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "GSK PLC": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "GSK": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "Glaxosmithkline plc": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "AstraZeneca PLC": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "AstraZeneca": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "阿斯利康": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "Sanofi SA": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "Sanofi": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "AbbVie, Inc.": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "AbbVie Inc": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "艾伯维": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "Bristol-Myers Squibb Co": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "NOVO NORDISK": { 地域: "其他", 主题: ["HALO"] },
  "Novo Nordisk": { 地域: "其他", 主题: ["HALO"] },
  "Novo Nordisk A/S": { 地域: "其他", 主题: ["HALO"] },
  "UNITEDHEALTH GROUP INC": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "UnitedHealth Group Inc": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "UnitedHealth Group, Inc.": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "联合健康": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "MEDTRONIC PLC": { 地域: "其他", 主题: ["HALO"] },
  "Medtronic PLC": { 地域: "其他", 主题: ["HALO"] },
  "美敦力": { 地域: "其他", 主题: ["HALO"] },
  "BOSTON SCIENTIFIC CORP": { 地域: "其他", 主题: ["HALO"] },
  "ELEVANCE HEALTH INC": { 地域: "其他", 主题: ["HALO"] },
  "Gilead Sciences, Inc.": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "吉利德科学": { 地域: "其他", 主题: ["HALO", "高股息"] },
  "Vertex Pharmaceuticals Inc": { 地域: "其他", 主题: ["HALO"] },
  "Intuitive Surgical, Inc.": { 地域: "其他", 主题: ["HALO"] },
  "Thermo Fisher Scientific Inc": { 地域: "其他", 主题: ["HALO"] },
  "HCA Healthcare": { 地域: "其他", 主题: ["HALO"] },
  "RECKITT BENCKISER GROUP PLC": { 地域: "其他", 主题: ["高股息"] },
  "McKesson Corp.": { 地域: "其他", 主题: ["HALO"] },
  "MCKESSON CORP": { 地域: "其他", 主题: ["HALO"] },

  // US Banks & Finance (高股息)
  "JPMORGAN CHASE & CO": { 地域: "其他", 主题: ["高股息"] },
  "JPMorgan Chase & Co.": { 地域: "其他", 主题: ["高股息"] },
  "摩根大通": { 地域: "其他", 主题: ["高股息"] },
  "Bank of America": { 地域: "其他", 主题: ["高股息"] },
  "美国银行": { 地域: "其他", 主题: ["高股息"] },
  "MORGAN STANLEY": { 地域: "其他", 主题: ["高股息"] },
  "Morgan Stanley": { 地域: "其他", 主题: ["高股息"] },
  "WELLS FARGO & CO NEW": { 地域: "其他", 主题: ["高股息"] },
  "Wells Fargo": { 地域: "其他", 主题: ["高股息"] },
  "CITIGROUP INC": { 地域: "其他", 主题: ["高股息"] },
  "花旗集团": { 地域: "其他", 主题: ["高股息"] },
  "AMERICAN EXPRESS CO": { 地域: "其他", 主题: ["高股息"] },
  "BERKSHIRE HATHAWAY INC DEL": { 地域: "其他", 主题: ["高股息"] },
  "Berkshire Hathaway": { 地域: "其他", 主题: ["高股息"] },
  "Charles Schwab": { 地域: "其他", 主题: ["高股息"] },
  "嘉信理财集团": { 地域: "其他", 主题: ["高股息"] },

  // Europe Banks (高股息)
  "BNP PARIBAS SA": { 地域: "其他", 主题: ["高股息"] },
  "BNP Paribas SA": { 地域: "其他", 主题: ["高股息"] },
  "法国兴业银行": { 地域: "其他", 主题: ["高股息"] },
  "UNICREDIT SPA": { 地域: "其他", 主题: ["高股息"] },
  "裕信银行": { 地域: "其他", 主题: ["高股息"] },
  "Intesa Sanpaolo SpA": { 地域: "其他", 主题: ["高股息"] },
  "意大利联合圣保罗银行": { 地域: "其他", 主题: ["高股息"] },
  "LLOYDS BANKING GROUP PLC": { 地域: "其他", 主题: ["高股息"] },
  "DEUTSCHE BANK AG": { 地域: "其他", 主题: ["高股息"] },
  "Deutsche Bank AG": { 地域: "其他", 主题: ["高股息"] },
  "德意志银行": { 地域: "其他", 主题: ["高股息"] },
  "ING GROEP NV": { 地域: "其他", 主题: ["高股息"] },
  "ING Groep NV": { 地域: "其他", 主题: ["高股息"] },
  "CAIXABANK SA": { 地域: "其他", 主题: ["高股息"] },
  "COMMERZBANK AG": { 地域: "其他", 主题: ["高股息"] },
  "DEUTSCHE BOERSE AG": { 地域: "其他", 主题: ["高股息"] },
  "Deutsche Boerse AG": { 地域: "其他", 主题: ["高股息"] },
  "Societe Generale SA": { 地域: "其他", 主题: ["高股息"] },
  "AIB GROUP PLC": { 地域: "其他", 主题: ["高股息"] },
  "爱尔兰联合银行": { 地域: "其他", 主题: ["高股息"] },
  "NatWest Group PLC": { 地域: "其他", 主题: ["高股息"] },
  "Barclays PLC": { 地域: "其他", 主题: ["高股息"] },
  "巴克莱银行": { 地域: "其他", 主题: ["高股息"] },
  "ALLIANZ SE": { 地域: "其他", 主题: ["高股息"] },
  "Allianz SE-Alv Gy": { 地域: "其他", 主题: ["高股息"] },
  "Allianz": { 地域: "其他", 主题: ["高股息"] },
  "ALLIANZ": { 地域: "其他", 主题: ["高股息"] },
  "AXA SA": { 地域: "其他", 主题: ["高股息"] },
  "MUENCHENER RUECKVERSICHERUNGS-GESELLSCHAFT AG IN MUENCHEN": { 地域: "其他", 主题: ["高股息"] },
  "Swiss Re AG": { 地域: "其他", 主题: ["高股息"] },
  "KB FINANCIAL GROUP INC": { 地域: "韩国", 主题: ["高股息"] },
  "KB Financial Group, Inc.": { 地域: "韩国", 主题: ["高股息"] },
  "HYUNDAI MOTOR CO": { 地域: "韩国", 主题: ["高股息"] },
  "SK INNOVATION CO LTD": { 地域: "韩国" },

  // Consumer (高股息)
  "VISA INC": { 地域: "其他", 主题: ["高股息"] },
  "Visa, Inc.": { 地域: "其他", 主题: ["高股息"] },
  "维萨卡": { 地域: "其他", 主题: ["高股息"] },
  "MASTERCARD INC A": { 地域: "其他", 主题: ["高股息"] },
  "万事达": { 地域: "其他", 主题: ["高股息"] },
  "COCA-COLA CO/THE": { 地域: "其他", 主题: ["高股息"] },
  "COCA-COLA": { 地域: "其他", 主题: ["高股息"] },
  "Nestle SA": { 地域: "其他", 主题: ["高股息"] },
  "Nestle SA (Packaged Foods & Meat)": { 地域: "其他", 主题: ["高股息"] },
  "Nestle": { 地域: "其他", 主题: ["高股息"] },
  "UNILEVER PLC": { 地域: "其他", 主题: ["高股息"] },
  "Carrefour SA": { 地域: "其他", 主题: ["高股息"] },
  "McDonald's": { 地域: "其他", 主题: ["高股息"] },
  "McDonald's Corp (Restaurants)": { 地域: "其他", 主题: ["高股息"] },
  "McDonalds": { 地域: "其他", 主题: ["高股息"] },
  "沃尔玛": { 地域: "其他", 主题: ["高股息"] },

  // Energy (高股息)
  "Shell PLC": { 地域: "其他", 主题: ["高股息"] },
  "Shell": { 地域: "其他", 主题: ["高股息"] },
  "壳牌": { 地域: "其他", 主题: ["高股息"] },
  "BP PLC": { 地域: "其他", 主题: ["高股息"] },
  "BP": { 地域: "其他", 主题: ["高股息"] },
  "TOTALENERGIES SE": { 地域: "其他", 主题: ["高股息"] },
  "TotalEnergies": { 地域: "其他", 主题: ["高股息"] },
  "道达尔": { 地域: "其他", 主题: ["高股息"] },
  "Exxon Mobil Corp": { 地域: "其他", 主题: ["高股息"] },
  "Exxon Mobil": { 地域: "其他", 主题: ["高股息"] },
  "埃克森美孚": { 地域: "其他", 主题: ["高股息"] },
  "Chevron": { 地域: "其他", 主题: ["高股息"] },
  "雪佛龙": { 地域: "其他", 主题: ["高股息"] },
  "Equinor ASA": { 地域: "其他", 主题: ["高股息"] },

  // Utilities (高股息)
  "NATIONAL GRID PLC": { 地域: "其他", 主题: ["高股息"] },
  "SSE plc": { 地域: "其他", 主题: ["高股息"] },
  "IBERDROLA SA": { 地域: "其他", 主题: ["高股息"] },
  "Iberdrola SA": { 地域: "其他", 主题: ["高股息"] },
  "Iberdrola": { 地域: "其他", 主题: ["高股息"] },
  "伊比德罗拉": { 地域: "其他", 主题: ["高股息"] },
  "ENGIE SA": { 地域: "其他", 主题: ["高股息"] },
  "Enel SpA": { 地域: "其他", 主题: ["高股息"] },
  "DEUTSCHE TELEKOM AG": { 地域: "其他", 主题: ["高股息"] },
  "Deutsche Telekom": { 地域: "其他", 主题: ["高股息"] },
  "Verizon Communications Inc": { 地域: "其他", 主题: ["高股息"] },
  "威瑞森通信": { 地域: "其他", 主题: ["高股息"] },
  "Vodafone Group PLC": { 地域: "其他", 主题: ["高股息"] },
  "SINGAPORE TELECOMMUNICATIONS LTD": { 地域: "新加坡", 主题: ["高股息"] },

  // Mining (高股息 leaders)
  "Rio Tinto Ltd.": { 地域: "其他", 主题: ["高股息"] },
  "Rio Tinto PLC": { 地域: "其他", 主题: ["高股息"] },
  "力拓集团": { 地域: "其他", 主题: ["高股息"] },
  "BHP Group Ltd.": { 地域: "其他", 主题: ["高股息"] },
  "VALE SA": { 地域: "其他", 主题: ["高股息"] },
  "淡水河谷": { 地域: "其他", 主题: ["高股息"] },
  "BARRICK MINING CORP": { 地域: "其他", 主题: ["HALO"] },
  "巴里克黄金公司": { 地域: "其他", 主题: ["HALO"] },
  "ANGLOGOLD ASHANTI PLC": { 地域: "其他", 主题: ["HALO"] },
  "安格鲁阿散蒂黄金有限公司": { 地域: "其他", 主题: ["HALO"] },
  "AGNICO EAGLE MINES LTD (ONTARIO)": { 地域: "其他", 主题: ["HALO"] },
  "ALAMOS GOLD INC": { 地域: "其他", 主题: ["HALO"] },
  "阿拉莫斯黄金": { 地域: "其他", 主题: ["HALO"] },
  "NEWMONT": { 地域: "其他", 主题: ["HALO"] },
  "纽蒙特黄金": { 地域: "其他", 主题: ["HALO"] },
  "纽蒙特黄金公司": { 地域: "其他", 主题: ["HALO"] },
  "PAN AMERICAN SILVER CORP": { 地域: "其他", 主题: ["HALO"] },
  "泛美白银公司": { 地域: "其他", 主题: ["HALO"] },
  "惠顿贵金属": { 地域: "其他", 主题: ["HALO"] },
  "金罗斯黄金": { 地域: "其他", 主题: ["HALO"] },
  "金罗斯黄金公司": { 地域: "其他", 主题: ["HALO"] },
  "IAMGOLD CORP": { 地域: "其他", 主题: ["HALO"] },
  "EQUINOX GOLD CORP": { 地域: "其他", 主题: ["HALO"] },
  "EVOLUTION MINING LTD": { 地域: "其他", 主题: ["HALO"] },
  "黄金": { 主题: ["HALO"] },
  "银": { 主题: ["HALO"] },
  "铜": { 主题: ["HALO"] },
  "铝": { 主题: ["HALO"] },

  // REITs (HALO)
  "DIGITAL RLTY TR INC": { 地域: "其他", 主题: ["HALO"] },
  "EQUINIX REIT INC": { 地域: "其他", 主题: ["HALO"] },
  "易昆尼克斯": { 地域: "其他", 主题: ["HALO"] },
  "IRON MOUNTAIN INC": { 地域: "其他", 主题: ["HALO"] },
  "铁山公司": { 地域: "其他", 主题: ["HALO"] },
  "WELLTOWER INC": { 地域: "其他", 主题: ["HALO"] },
  "PUBLIC STORAGE": { 地域: "其他", 主题: ["HALO"] },
  "PUBLIC STORAGE REIT": { 地域: "其他", 主题: ["HALO"] },
  "EQUITY RESIDENTIAL REIT": { 地域: "其他", 主题: ["HALO"] },
  "AGREE REALTY REIT CORP": { 地域: "其他", 主题: ["HALO"] },
  "CAMDEN PROPERTY TRUST": { 地域: "其他", 主题: ["HALO"] },
  "INVITATION HOMES INC": { 地域: "其他", 主题: ["HALO"] },
  "CARETRUST REIT INC": { 地域: "其他", 主题: ["HALO"] },
  "ALEXANDRIA REAL ESTATE EQUITIES RE": { 地域: "其他", 主题: ["HALO"] },
  "HEALTHPEAK PROPERTIES": { 地域: "其他", 主题: ["HALO"] },
  "GOODMAN GROUP UNITS": { 地域: "其他", 主题: ["HALO"] },
  "普洛斯公司": { 地域: "其他", 主题: ["HALO"] },
  "西蒙地产集团": { 地域: "其他", 主题: ["HALO"] },

  // ══════════════════════════════════════════════
  // BONDS
  // ══════════════════════════════════════════════

  // 投资级别债 — Bond ETFs
  "ISH S TRES BND 7-10 ETF USD": { 债券: "投资级别债" },
  "ISHARES CORE EUR GOVT BOND UCI EUR": { 债券: "投资级别债" },
  "ISHARES $ TREASURY BOND 1-3YR UCIT": { 债券: "投资级别债" },
  "ISH-S $ TRSY BOND 3-7 YR UCITS ETF": { 债券: "投资级别债" },
  "ISHARES $ CORP BOND UCITS ETF USD": { 债券: "投资级别债" },
  "ISHARES S CORP BOND UCITS ETF USD": { 债券: "投资级别债" },
  "ISHARES CORE EURO CORP BOND ETF": { 债券: "投资级别债" },
  "ISHARES CORP BD 0-3YR ESG SRI ETF ACC": { 债券: "投资级别债" },
  "ISHARES $ ULTRASHORT BOND UCITS ETF USD": { 债券: "投资级别债" },
  "ISHARES $ FLOATING RATE BD UCITS ETF USD": { 债券: "投资级别债" },
  "INVERSCO US TRS BD 1-3 YR ETF USD ACC": { 债券: "投资级别债" },
  "VANGUARD USD CORPO 1-3 YEAR BD UCITS ETF": { 债券: "投资级别债" },
  "INVERSCO US TRS BD 1-3 YR ETF USD ACC": { 债券: "投资级别债" },
  "INVESCO US TRS BD 1-3 YR ETF USD ACC": { 债券: "投资级别债" },

  // 投资级别债 — US Treasuries
  "USTB 4.5% 11/15/54": { 债券: "投资级别债" },
  "USTB 4.625% 05/15/44": { 债券: "投资级别债" },
  "USTN 3.75% 08/31/31": { 债券: "投资级别债" },
  "USTN 4% 07/31/29": { 债券: "投资级别债" },
  "USTN 4.25% 01/31/30": { 债券: "投资级别债" },
  "USTN 4.25% 05/15/35": { 债券: "投资级别债" },
  "USTN 4.375% 01/31/32": { 债券: "投资级别债" },
  "USTN 4.625% 02/15/35": { 债券: "投资级别债" },
  "USTN 4.875% 10/31/28": { 债券: "投资级别债" },
  "USTN 4.25% 01/15/34": { 债券: "投资级别债" },
  "USTN 4.25% 11/15/34": { 债券: "投资级别债" },
  "TREASURY NOTE 4.125 07/31/2028": { 债券: "投资级别债" },
  "TREASURY BILL null% 09/04/2024": { 债券: "投资级别债" },
  "TREASURY BILL null% 14/03/2024": { 债券: "投资级别债" },
  "TREASURY BILL null% 23/04/2024": { 债券: "投资级别债" },
  "US T 1.125% 29022028": { 债券: "投资级别债" },
  "US T 2.250% 15082027": { 债券: "投资级别债" },
  "US T 3.625% 31052028": { 债券: "投资级别债" },
  "US T 3.625% 31082029": { 债券: "投资级别债" },
  "US T 3.875% 31072027": { 债券: "投资级别债" },
  "US T 4.250% 31012030": { 债券: "投资级别债" },
  "US TREASURY N/B FIX 2.750% 15.08.32": { 债券: "投资级别债" },
  "US TREASURY N/B FIX 3.500% 15.10.28": { 债券: "投资级别债" },
  "US TREASURY N/B FIX 3.875% 30.09.32": { 债券: "投资级别债" },
  "US TREASURY N/B FIX 4.250% 15.05.35": { 债券: "投资级别债" },
  "US TREASURY N/B FIX 4.250% 15.11.34": { 债券: "投资级别债" },
  "US TREASURY N/B FIX 4.375% 15.05.34": { 债券: "投资级别债" },
  "US TSY 20/11/2025": { 债券: "投资级别债" },
  "US TSY 4.00% 31/03/2030": { 债券: "投资级别债" },
  "US TSY 4.13% 31/10/2027": { 债券: "投资级别债" },
  "US TSY 4.63% 30/04/2029": { 债券: "投资级别债" },
  "TSY INFL IX N/B ILX FIX 0.125% 15.01.32": { 债券: "投资级别债" },
  "US Department of The Treasury 3.63% 31/10/30": { 债券: "投资级别债" },
  "US Department of The Treasury 3.88% 30/06/30": { 债券: "投资级别债" },
  "US Department of The Treasury 4.25% 15/05/25": { 债券: "投资级别债" },
  "United States Treasury Bill": { 债券: "投资级别债" },
  "United States Treasury Bond": { 债券: "投资级别债" },
  "United States Treasury Bond 3.875 Apr 30 30": { 债券: "投资级别债" },
  "United States Treasury Note/Bond 3.875 Jun 30 30": { 债券: "投资级别债" },
  "United States Treasury Note/Bond 4,000 Mar 31 30": { 债券: "投资级别债" },
  "United States Treasury Note/Bond 4.000 Mar 31 30": { 债券: "投资级别债" },
  "United States Treasury Note/Bond 4.250 May 15 35": { 债券: "投资级别债" },
  "United States Treasury Note/Bond, Unsecured, 4.25%, 11/15/34": { 债券: "投资级别债" },

  // 投资级别债 — Europe Govts
  "DEUTSCHLAND 2.20% 15/02/2034": { 债券: "投资级别债" },
  "GERMANY (FEDERAL REPUBLIC OF) 0.0000 18/03/2026 SERIES 364D": { 债券: "投资级别债" },
  "GERMANY (FEDERAL REPUBLIC OF) 2.3 02/15/2033": { 债券: "投资级别债" },
  "Bundesobligation 2.400 Apr 18 30": { 债券: "投资级别债" },
  "French Republic 3.50% 25/11/35": { 债券: "投资级别债" },
  "BONOS Y OBLIG DEL ESTADO FIX 1.900% 31.10.52": { 债券: "投资级别债" },
  "BONOS Y OBLIG DEL ESTADO FIX 4.000% 31.10.54": { 债券: "投资级别债" },
  "Secretaria General Del Tesoro Y Financiacion Internacional 4.00% 31/10/54": { 债券: "投资级别债" },
  "Spain Government Bond, SR UNSECURED, Sr Unsecured, REG S, 144A, 3.15%, 4/30/35": { 债券: "投资级别债" },
  "Italy Buoni Poliennali Del Tesoro 4.30% 07/10/54": { 债券: "投资级别债" },
  "Republic of Italy 3.65% 01/08/35": { 债券: "投资级别债" },
  "UK CONV GILT 1.25 07/22/2027": { 债券: "投资级别债" },
  "United Kingdom Gilt 0.500 Jan 31 29": { 债券: "投资级别债" },
  "United Kingdom Gilt 4.125 Jul 22 29": { 债券: "投资级别债" },
  "United Kingdom of Great Britain And Northern Ireland 4.50% 07/03/35": { 债券: "投资级别债" },
  "AUSTRALIA (COMMONWEALTH OP) 1 11/21/2031": { 债券: "投资级别债" },
  "New South Wales Treasury Corp, LOCAL GOVT GUARN, Sr Unsecured, 2.00%, 3/8/33": { 债券: "投资级别债" },
  "Treasury Corp of Victoria, LOCAL GOVT GUARN, Sr Unsecured, MTN, 2.00%, 11/20/37": { 债券: "投资级别债" },
  "NZ T 1.500% 15052031": { 债券: "投资级别债" },
  "NZ T 4.500% 15052030": { 债券: "投资级别债" },
  "POLAND (REPUBLIC OF) 4.5 01/25/2031": { 债券: "投资级别债" },
  "POLAND (REPUBLIC OF) 5 10/25/2034": { 债券: "投资级别债" },
  "POLAND (REPUBLIC OF) 5 10/25/2035": { 债券: "投资级别债" },
  "POLAND 1.75% 25/04/2032": { 债券: "投资级别债" },
  "Government of Norwegian, Reg S, 1.75%, 2/17/27": { 债券: "投资级别债" },

  // 投资级别债 — IG Corporates
  "CITIGROUP INC 3.493 10/22/2034": { 债券: "投资级别债" },
  "JPMORGAN CHASE & CO 2.9630 25/01/2033 SERIES CORP": { 债券: "投资级别债" },
  "BANK OF AMERICA CORP 2.9720 04/02/2033 SERIES MTN": { 债券: "投资级别债" },
  "BANK OF AMERICA CORP MTN 5.872 09/15/2034": { 债券: "投资级别债" },
  "MORGAN STANLEY - 5.9480 01/19/38": { 债券: "投资级别债" },
  "MORGAN STANLEY 5.1920 17/04/2031 SERIES CORP": { 债券: "投资级别债" },
  "MORGAN STANLEY 5.466 01/18/2035": { 债券: "投资级别债" },
  "WELLS FARGO & COMPANY 5.4990 23/01/2035 SERIES CORP": { 债券: "投资级别债" },
  "WELLS FARGO & COMPANY - CPR 7.5000 03/15/98": { 债券: "投资级别债" },
  "AMAZON.COM INC 5.4500 20/11/2055 SERIES CORP": { 债券: "投资级别债" },
  "BOOKING HOLDINGS INC 4.0000 01/03/2044 SERIES CORP": { 债券: "投资级别债" },
  "Pfizer Investment Enterprises 5.300 May 19 53": { 债券: "投资级别债" },
  "CREDIT AGRICOLE 3.80% 30/04/2031": { 债券: "投资级别债" },
  "BPCE SA MTN REGS 3.625 10/01/2033": { 债券: "投资级别债" },
  "UBS GROUP AG REGS 3.25 02/12/2034": { 债券: "投资级别债" },
  "DEUTSCHE BANK (NY BRNCH)(FXD-FLT) 5.297 05/09/2031": { 债券: "投资级别债" },
  "E.ON SE MTN REGS 3.448 01/19/2034": { 债券: "投资级别债" },
  "FOXCONN SINGAPORE PTE LTD MTN REGS 3.125 11/04/2031": { 债券: "投资级别债" },
  "Alibaba 2.700 Feb 09 41": { 债券: "亚洲债" },
  "Lenovo 6.536 Jul 27 32": { 债券: "亚洲债" },
  "SINO CHEM O 2.375% 09/23/31 RGS": { 债券: "亚洲债" },
  "CNAC HK FIN 3% 09/22/30 RGS": { 债券: "亚洲债" },
  "CHINA 3.12% 25/10/2052": { 债券: "亚洲债" },
  "CHINA 3.60% 21/05/2030": { 债券: "亚洲债" },
  "CHINA": { 债券: "亚洲债" },
  "People'S Republic of China 2.04% 25/11/34": { 债券: "亚洲债" },
  "Government of Japan 2.30% 20/12/54": { 债券: "投资级别债" },
  "KOREA 1.13% 10/09/2039": { 债券: "投资级别债" },
  "Korea Treasury Bond, BONDS, Sr Unsecured, 2809, 3.50%, 9/10/28": { 债券: "投资级别债" },
  "KOREA EAST WEST 4% 5/4/31 RGS": { 债券: "投资级别债" },
  "EXPT IMP BK KR 4.375% 01/13/36": { 债券: "投资级别债" },
  "HANWHA LI 6.3%/VAR 6/24/55 RGS": { 债券: "投资级别债" },
  "Dai-ichi Life Insurance 6.200 Perp": { 债券: "投资级别债" },
  "Meiji Yasuda Life Insurance 5.800 Sep 11 54": { 债券: "投资级别债" },
  "Shanghai Commercial Bank 6.375 Feb 28 33": { 债券: "亚洲债" },
  "MTR CORPORATION CL LTD NC10.5 MTN REGS 5.625 12/31/2079": { 债券: "亚洲债" },
  "Bocom Leasing Management Hong Kong FRN Jun 26 27": { 债券: "亚洲债" },
  "Haidilao International 2.150 Jan 14 26": { 债券: "亚洲债" },
  "State Grid Europe Development 2014 3.250 Apr 07 27": { 债券: "亚洲债" },
  "YONGDA Investment 4.600 Jun 03 28": { 债券: "亚洲债" },
  "Media Investment Development 2.880 Feb 24 27": { 债券: "亚洲债" },

  // 新兴市场债
  "ISHARES JPM EM LCAL GVT BD ETF DST": { 债券: "新兴市场债" },
  "ISHR EM MKT GOV BD IDX (LU) X2 USD": { 债券: "新兴市场债" },
  "PRINCIPAL GI FIN UNCON EM FX INC I2 ACC": { 债券: "新兴市场债" },
  "India Government Bond, SR UNSECURED, Sr Unsecured, 7.18%, 8/14/33": { 债券: "新兴市场债" },
  "India Government Bond, SR UNSECURED, Sr Unsecured, 6.70%, 10/07/34": { 债券: "新兴市场债" },
  "India Government Bond, Sr.UNSECURED, Sr.Unsecured, 6.79%, 10/07/34": { 债券: "新兴市场债" },
  "India Government Bond, Sr.UNSECURED, Sr.Unsecured, 7.18%, 8/14/33": { 债券: "新兴市场债" },
  "REPUBLIC OF IND 8.5% 10/35 RGS": { 债券: "新兴市场债" },
  "FTGF WA India Bd Fd": { 债券: "新兴市场债" },
  "Malaysia Government Bond, BONDS, Sr Unsecured, 0417, 3.899%, 11/16/27": { 债券: "新兴市场债" },
  "Malaysia Government Bond, BONDS, Sr Unsecured, 0310, 4.488%, 4/15/30": { 债券: "新兴市场债" },
  "Malaysia Government Bond, BONDS, Sr Unsecured, D417, 3.899%, 11/16/27": { 债券: "新兴市场债" },
  "Malaysia Government Bond, BONDS, Sr.Unsecured, 0417, 3.899%, 11/16/27": { 债券: "新兴市场债" },
  "MALAYSIA 4.64% 07/11/2033": { 债券: "新兴市场债" },
  "MALAYSIA": { 债券: "新兴市场债" },
  "PETRONAS CAP 5.34% 4/35 RGS": { 债券: "新兴市场债" },
  "INDONESIA 7.00% 15/05/2027": { 债券: "新兴市场债" },
  "INDONESIA 7.13% 15/06/2043": { 债券: "新兴市场债" },
  "INDONESIA GOVT 6.625% 2/37 RGS": { 债券: "新兴市场债" },
  "Indonesia Treasury Bond, BONDS, Unsecured, FR96, 7.00%, 2/15/33": { 债券: "新兴市场债" },
  "PERUSAHAAN LISTRIK NEGARA (PERSERO) MTN REGS 1.875 11/05/2031": { 债券: "新兴市场债" },
  "PHILIPPINE GOVT 3.95% 01/20/40": { 债券: "新兴市场债" },
  "PHILIPPINES 6.25% 14/01/2036": { 债券: "新兴市场债" },
  "Philippine Government Bond, BONDS, Sr Unsecured, 0770, 6.375%, 7/27/30": { 债券: "新兴市场债" },
  "THAILAND 3.30% 17/06/2038": { 债券: "新兴市场债" },
  "Brazil Notes do Tesouro Nacional Serie F, NOTES, Unsecured, NTNF, 9.46141%, 10/1/31": { 债券: "新兴市场债" },
  "Brazil Notas do Tesouro Nacional Serie F, NOTES, Unsecured, NTNF, 9.46141%, 10/1/31": { 债券: "新兴市场债" },
  "Brazil Notas do Tesouro Nacional Serie F, NOTES, Unsecured, NTNF, 9.46141%, 10/1/33": { 债券: "新兴市场债" },
  "Brazil Notes do Tesouro Nacional Serie F, NOTES, Unsecured, NTNF, 9.46141%, 10/1/33": { 债券: "新兴市场债" },
  "BRAZIL FEDERATIVE REPUBLIC OF (GOV 10 01/01/2029": { 债券: "新兴市场债" },
  "BRAZIL FEDERATIVE REPUBLIC OF (GOV 10 01/01/2031": { 债券: "新兴市场债" },
  "NOTA DO TESOURO NACIONAL NTNF FIX 10.000% 01.01.35": { 债券: "新兴市场债" },
  "Noda do Tesouro Nacional, 10.00%, 10/1/25": { 债券: "新兴市场债" },
  "Nota do Tesouro Nacional, 10.00%, 10/1/29": { 债券: "新兴市场债" },
  "MEXICO (UNITED MEXICAN STATES) (GO 7.5 05/29/2031": { 债券: "新兴市场债" },
  "MEXICO (UNITED MEXICAN STATES) (GO 8.5 02/28/2030": { 债券: "新兴市场债" },
  "MEXICO 7.75% 13/11/2042": { 债券: "新兴市场债" },
  "COLOMBIA (REPUBLIC OF) 7 03/26/2031": { 债券: "新兴市场债" },
  "Colombian TES, BONDS, Unsecured, 6.925%, 5/28/42": { 债券: "新兴市场债" },
  "Colombian TES, BONDS, Unsecured, 8.325%, 5/28/42": { 债券: "新兴市场债" },
  "Colombian TES, BONDS, Unsecured, 8.925%, 5/28/42": { 债券: "新兴市场债" },
  "Colombian TES, BONDS, Unsecured, B, 9.25%, 5/28/42": { 债券: "新兴市场债" },
  "PERU (REPUBLIC OF) 7.3 08/12/2033": { 债券: "新兴市场债" },
  "Kazakhstan Government Bond - MEUKAM, BONDS, Unsecured, 10YR, 10.30%, 3/17/31": { 债券: "新兴市场债" },
  "Marshall Islands Government Bond, BONDS, Sr Unsecured, 0316, 3.90%, 11/30/26": { 债券: "新兴市场债" },
  "Government of South Africa, 5.00%, 1/31/40": { 债券: "新兴市场债" },
  "Government of South Africa, 8.00%, 1/31/40": { 债券: "新兴市场债" },
  "Government of South Africa, 8.75%, 1/31/44": { 债券: "新兴市场债" },
  "Government of South Africa, 9.00%, 1/31/40": { 债券: "新兴市场债" },
  "Government of South Africa, 9.05%, 15/1/40": { 债券: "新兴市场债" },
  "SOUTH AFRICA (REPUBLIC OF) 8.25 03/31/2032": { 债券: "新兴市场债" },
  "SOUTH AFRICA 6.50% 28/02/2041": { 债券: "新兴市场债" },
  "Republic of Kenya Government International Bond, SR UNSECURED, Sr Unsecured, REGS, 9.375%, 2/16/31": { 债券: "新兴市场债" },
  "ECUADOR REPUBLIC OF, senior bond, Reg S, 6.90%, 7/31/35": { 债券: "新兴市场债" },
  "Uruguay Government International Bond, 3.875%, 7/02/40": { 债券: "新兴市场债" },
  "Upgraya Government International Bond, 3.875%, 7/02/40": { 债券: "新兴市场债" },

  // 垃圾债 (High Yield)
  "ISHARES $ SHT DURATION HY CRP BD UCITS E": { 债券: "垃圾债" },
  "ISHARES - AAA CLO ACTIVE U EURHA": { 债券: "垃圾债" },
  "GREENKO (JPM STRUCTURED) MTN 13 02/03/2028": { 债券: "垃圾债" },
  "MUMBAI INTERNATIONAL AIRPORT LTD REGS 6.95 07/30/2029": { 债券: "垃圾债" },
  "RESURGENT TRADE & INVESTMENT LTD REGS 9.52 12/05/2027": { 债券: "垃圾债" },
  "ACROPOLIS TRADE & INVESTMENTS PIK REGS 11.035 04/02/2028": { 债券: "垃圾债" },
  "METRO BANK HOLDINGS PLC REGS 12 04/30/2029": { 债券: "垃圾债" },
  "BARCLAYS PLC REGS 8.875 12/31/2079": { 债券: "垃圾债" },
  "NATIONWIDE BUILDING SOCIETY REGS 5.75 12/31/2079": { 债券: "垃圾债" },
  "MINOR INTERNATIONAL PCL REGS 2.7 12/31/2079": { 债券: "垃圾债" },
  "BHARTI AIRTEL 3.25% 6/3/31 RGS": { 债券: "垃圾债" },
  "COTY INC 5.6000 15/01/2031 SERIES 144A": { 债券: "垃圾债" },
  "MICROCHIP TECHNOLOGY INC CPR 7.5000 03/15/28 (美国)": { 债券: "垃圾债" },
  "LUMENTUM HOLDINGS INC - 144A 0.3750 03/15/32": { 债券: "垃圾债" },
  "LUMENTUM HOLDINGS INC 0.3750 03/15/32 (美国)": { 债券: "垃圾债" },
  "LUMENTUM HOLDINGS INC 0.5000 06/15/28": { 债券: "垃圾债" },
  "MACOM TECH SOLUTIONS 0.0000 12/15/29": { 债券: "垃圾债" },
  "MKS INC 1.2500 06/01/30": { 债券: "垃圾债" },
  "MKS INC 1.2500 06/01/30 (美国)": { 债券: "垃圾债" },
  "WESTERN DIGITAL CORP - 3.0000 11/15/28": { 债券: "垃圾债" },
  "Bausch Health Companies Inc.": { 债券: "垃圾债" },
  "LifePoint Health": { 债券: "垃圾债" },
  "Novolex Holdings, Inc.": { 债券: "垃圾债" },
  "Radiology Partners": { 债券: "垃圾债" },
  "Herbalife Ltd.": { 债券: "垃圾债" },
  "EchoStar": { 债券: "垃圾债" },
  "Sunoco LP": { 债券: "垃圾债" },
  "Petroleos Mexicanos": { 债券: "垃圾债" },
  "STANDARD LIFE ABERDEEN PLC REGS 4.25 06/30/2028": { 债券: "垃圾债" },
  "镍业有限公司 9.00% 30/09/2030": { 债券: "垃圾债" },
  "Studio城市金融有限公司 5.00% 15/01/2029": { 债券: "亚洲债" },
  "IMCD NV REGS 3.625 04/30/2030": { 债券: "垃圾债" },
  "EUSTREAM AS REGS 1.625 06/25/2027": { 债券: "投资级别债" },
};
