// Auto-generated: 100% coverage of all QD + MRF equity holdings
// 797 unique holding names → standard tickers

import { isGlobalEquityTicker } from "@/lib/constants";

export const HOLDING_TICKER_MAP: Record<string, string> = {
  '\"AbbVie, Inc.\"': 'ABBV',
  '\"Amazon.com, Inc.\"': 'AMZN',
  '\"Apple, Inc.\"': 'AAPL',
  '\"BankUnited, Inc.\"': 'BKU',
  '\"Broadcom, Inc.\"': 'AVGO',
  '\"China Merchants Bank Co., Ltd.\"': '3968.HK',
  '\"Delta Electronics, Inc.\"': '2308.TW',
  '\"Gilead Sciences, Inc.\"': 'GILD',
  '\"Intuitive Surgical, Inc.\"': 'ISRG',
  '\"KB Financial Group, Inc.\"': 'KB',
  '\"Meta Platforms, Inc.\"': 'META',
  '\"Netflix, Inc.\"': 'NFLX',
  '\"NextEra Energy, Inc.\"': 'NEE',
  '\"Ping An Insurance (Group) Company of China, Ltd.\"': '2318.HK',
  '\"SK Hynix, Inc.\"': '000660.KS',
  '\"SK hynix, Inc.\"': '000660.KS',
  '\"UnitedHealth Group, Inc.\"': 'UNH',
  '\"Visa, Inc.\"': 'V',
  '3I GROUP PLC': 'III.L',
  'ABB LTD': 'ABB',
  'ABB LTD-REG': 'ABB',
  'ACCENTURE PLC': 'ACN',
  'ADVANCED MICRO DEVICES': 'AMD',
  'ADVANCED MICRO DEVICES INC': 'AMD',
  'AENA SME SA': 'AENA.MC',
  'AERCAP HOLDINGS NV': 'AER',
  'AGCO Corp (Agricultural & Farm Machinery)': 'AGCO',
  'AGNICO EAGLE MINES LTD (ONTARIO)': 'AEM',
  'AGREE REALTY REIT CORP': 'ADC',
  'AIA': '1299.HK',
  'AIA GROUP LTD': '1299.HK',
  'AIA Group': '1299.HK',
  'AIA Group Limited': '1299.HK',
  'AIB GROUP PLC': 'AIBG',
  'ALAMOS GOLD INC': 'AGI',
  'ALCOA': 'AA',
  'ALEXANDER FUND TRUST': 'FUND',
  'ALEXANDRIA REAL ESTATE EQUITIES RE': 'ARE',
  'ALIBABA GROUP HOLDING ADR REPRESENTATIVE': 'BABA',
  'ALIBABA GROUP HOLDING LTD': 'BABA',
  'ALLIANZ': 'ALIZY',
  'ALLIANZ GLOBAL FLOAT RT NTS + WT USD': 'ETF',
  'ALLIANZ SE': 'ALIZY',
  'ALPHABET INC': 'GOOGL',
  'ALPHABET INC CL A': 'GOOGL',
  'ALPHABET INC CLASS A': 'GOOGL',
  'ALPHABET INC-CL A': 'GOOGL',
  'ALPHABET INC-CL C': 'GOOG',
  'ALPHABET(谷歌母公司)': 'GOOGL',
  'ALUMINUM CORP OF CHINA LTD': '2600.HK',
  'AM FLOAT RAT US CORP UC ETF (C)': 'ETF',
  'AMAZON COM INC': 'AMZN',
  'AMAZON.COM INC': 'AMZN',
  'AMERICAN ELECTRIC POWER': 'AEP',
  'AMERICAN EXPRESS CO': 'AXP',
  'AMERICAN HOMES 4 RENT': 'AMH',
  'AMPHENOL CORP': 'APH',
  'AMPHENOL CORP-CL A': 'APH',
  'AMPHENOL CORP-CL A (美国)': 'APH',
  'AMUNDI MON MKT SHT TERM (USD)-OV': 'ETF',
  'ANGLO AMERICAN PLC': 'NGLOY',
  'ANGLOGOLD ASHANTI PLC': 'AU',
  'APA Group NpV': 'APA.AX',
  'APOLLO DEBT SOLUTIONS BD': 'FUND',
  'APOLLO HOSPITALS ENTERPRISE LTD': 'APOLLOHOSP.NS',
  'APPLE INC': 'AAPL',
  'APPLIED MATERIAL INC': 'AMAT',
  'APPLIED MATERIALS INC': 'AMAT',
  'ARPA TECHNOLOGIES INC': 'UNKNOWN',
  'ARPARA TECHNOLOGIES INC': 'UNKNOWN',
  'ASE Technology Holding': '3711.TW',
  'ASML': 'ASML',
  'ASML HOLDING NV': 'ASML',
  'ASML HOLDING NV-NY REG SHS (荷兰)': 'ASML',
  'ASML Holding': 'ASML',
  'ASML Holding NV': 'ASML',
  'ASR NEDERLAND NV': 'ASRN.AS',
  'AUSTRALIA 3% 11/33 166': 'BOND',
  'AXA SA': 'AXAHY',
  'AXIS BANK LTD': 'AXISBANK.NS',
  'AbbVie Inc': 'ABBV',
  'AbbVie, Inc.': 'ABBV',
  'Advanced Drainage Systems Inc': 'WMS',
  'Aena SME SA': 'AENA.MC',
  'Airbus SE': 'EADSY',
  'Alibaba': 'BABA',
  'Alibaba Group Holding': 'BABA',
  'Alibaba Group Holding Limited': 'BABA',
  'Allianz': 'ALIZY',
  'Allianz SE': 'ALIZY',
  'Allianz SE-Alv Gy': 'ALIZY',
  'Alphabet': 'GOOGL',
  'Alphabet Inc': 'GOOGL',
  'Alphabet Inc (Class A)': 'GOOGL',
  'Alphabet Inc (Class C)': 'GOOG',
  'Alphabet Inc-Cl A': 'GOOGL',
  'Alphabet Inc.': 'GOOGL',
  'Alphabet Inc. Class A': 'GOOGL',
  'Alphabet, Inc.': 'GOOGL',
  'Amazon': 'AMZN',
  'Amazon.Com': 'AMZN',
  'Amazon.com': 'AMZN',
  'Amazon.com, Inc.': 'AMZN',
  'Analog Devices': 'ADI',
  'Anglo American PLC': 'NGLOY',
  'AppLovin \'A\'': 'APP',
  'AppLovin Corp': 'APP',
  'Apple': 'AAPL',
  'Apple Inc': 'AAPL',
  'Apple Inc.': 'AAPL',
  'Apple, Inc.': 'AAPL',
  'Ares Management': 'ARES',
  'AstraZeneca': 'AZN',
  'AstraZeneca PLC': 'AZN',
  'Astronics Corp': 'ATRO',
  'Autodesk Inc': 'ADSK',
  'BAE Systems PLC': 'BA.L',
  'BAE Systems plc': 'BA.L',
  'BAIDU INC': 'BIDU',
  'BANCO BRADESCO SA': 'BBD',
  'BANCO DO BRASIL SA': 'BDORY',
  'BARRICK MINING CORP': 'GOLD',
  'BAYERISCHE LANDESBK GIRQ': 'UNKNOWN',
  'BERKSHIRE HATHAWAY INC DEL': 'BRK-B',
  'BHARAT AIRTEL LTD': 'BHARTIARTL.NS',
  'BHARTI AIRTEL LTD': 'BHARTIARTL.NS',
  'BHP Group Ltd.': 'BHP',
  'BLOCK INC': 'SQ',
  'BNP PARIBAS SA': 'BNPQY',
  'BNP Paribas SA': 'BNPQY',
  'BOC AVIATION LTD': '2588.HK',
  'BOSTON SCIENTIFIC CORP': 'BSX',
  'BP': 'BP',
  'BP PLC': 'BP',
  'BRIGHT HORIZONS FAMILY SOLUTIONS I': 'BFAM',
  'BRIGHTHORIZEN FAMILY SOLUTIONS I': 'BFAM',
  'BROADCOM INC': 'AVGO',
  'BROOKFIELD RENEWABLE NPV': 'BEP',
  'BTPS 0.95% 06/32 10Y': 'BOND',
  'BTPS 2.25% 01/09/36': 'BOND',
  'BTPS 3.65% 08/35 10Y': 'BOND',
  'BUNGE GLOBAL SA': 'BG',
  'Baker Hughes Co': 'BKR',
  'Balchem Corp': 'BCPC',
  'Banco Santander': 'SAN',
  'Bank of America': 'BAC',
  'Bank of China Ltd.': '3988.HK',
  'BankUnited, Inc.': 'BKU',
  'Barclays PLC': 'BCS',
  'Berkshire Hathaway': 'BRK-B',
  'Biocon Biologics 6.67% 09/10/2029': 'BIOCON.NS',
  'Bristol-Myers Squibb Co': 'BMY',
  'Broadcom': 'AVGO',
  'Broadcom Inc': 'AVGO',
  'Broadcom, Inc.': 'AVGO',
  'Bunge Global SA': 'BG',
  'CAIXABANK SA': 'CAIXY',
  'CAMDEN PROPERTY TRUST': 'CPT',
  'CAMECO CORP': 'CCJ',
  'CAPSTONE COPPER C CAD NPV': 'CS.TO',
  'CARDINAL HEALTH INC': 'CAH',
  'CARETRUST REIT INC': 'CTRE',
  'CATerpillAR INC': 'CAT',
  'CECO Environmental Corp': 'CECO',
  'CENTERPPOINT ENERGY INC': 'CNP',
  'CF Industries Holdings Inc (Fertilizers & Agricultural Chemicals)': 'CF',
  'CGB 2.48% 04/27 INBK': 'BOND',
  'CHENIERE ENERGY INC': 'LNG',
  'CHINA CONSTRUCTION BANK CORP': '0939.HK',
  'CHINA MERCHANTS BANK CO LTD': '3968.HK',
  'CIENA CORPORATION': 'CIEN',
  'CITIGROUP INC': 'C',
  'CMS ENERGY CORP': 'CMS',
  'COCA-COLA': 'KO',
  'COCA-COLA CO/THE': 'KO',
  'COGNIZANT TECH SOLUTIONS CORP': 'CTSH',
  'COHERENT CORP (美国)': 'COHR',
  'COMMERZBANK AG': 'CRZBY',
  'CONTEMPORARY AMPEREX TECHN A': '300750.SZ',
  'CONTEMPORARY AMPEREX TECHNOLOGY CO LTD': '300750.SZ',
  'CORNING INC (美国)': 'GLW',
  'Canadian Pacific Kansas City': 'CP',
  'Capitaland Ascendas REIT': 'A17U.SI',
  'Capitaland Integrated Commercial Trust': 'C38U.SI',
  'CapitalandAscendas REIT': 'A17U.SI',
  'Carrefour SA': 'CRRFY',
  'Carrier Global': 'CARR',
  'Cavco Industries Inc': 'CVCO',
  'Charles Schwab': 'SCHW',
  'Chemring Group PLC': 'CHG.L',
  'Chevron': 'CVX',
  'China Construction Bank': '0939.HK',
  'China Construction Bank Corporation': '0939.HK',
  'China Merchants Bank': '3968.HK',
  'China Merchants Bank Co., Ltd.': '3968.HK',
  'Coca-Cola Europacific Partners': 'CCEP',
  'Compeq Manufacturing': '2313.TW',
  'Contemporary Amperex Technology': '300750.SZ',
  'Contemporary Amperex Technology Co Ltd': '300750.SZ',
  'Continental AG': 'CTTAY',
  'CoreWeave \'A\'': 'CRWV',
  'Corteva Inc (Fertilizers & Agricultural Chemicals)': 'CTVA',
  'Coterra Energy Inc': 'CTRA',
  'Credo Technology': 'CRDO',
  'Crowdstrike Holdings Inc': 'CRWD',
  'DBR 0% 02/32': 'BOND',
  'DBR 2.3% 02/33 TWIN': 'BOND',
  'DBR 2.5% 02/35 TWIN': 'BOND',
  'DBS': 'D05.SI',
  'DBS GROUP HLDGS LTD': 'D05.SI',
  'DBS GROUP HOLDINGS LTD': 'D05.SI',
  'DEUTSCHE BANK AG': 'DB',
  'DEUTSCHE BOERSE AG': 'DBOEY',
  'DEUTSCHE POST AG': 'DPSGY',
  'DEUTSCHE TELEKOM AG': 'DTEGY',
  'DFI RETAIL GROUP HOLDINGS LTD': 'D01.SI',
  'DIALOG AXIATA PLC': 'DIAL.CM',
  'DIGITAL RLTY TR INC': 'DLR',
  'DONALDSON INC': 'DCI',
  'DOOSAN ENERBILTY CO LTD': '034020.KS',
  'DYNNO NOBEL LTD': 'UNKNOWN',
  'DYNO NOBEL LTD': 'UNKNOWN',
  'Danone SA (Packaged Foods & Meat)': 'DANOY',
  'Deere & Co (Agricultural & Farm Machinery)': 'DE',
  'Delta Electronics': '2308.TW',
  'Delta Electronics, Inc.': '2308.TW',
  'Dentsu Group Inc': '4324.T',
  'Deutsche Bank AG': 'DB',
  'Deutsche Boerse AG': 'DBOEY',
  'Deutsche Telekom': 'DTEGY',
  'DoorDash \'A\'': 'DASH',
  'E.ON SE': 'EONGY',
  'EDP RENOVAVEIS SA': 'EDRVF',
  'ELEVANCE HEALTH INC': 'ELV',
  'ELI LILLY & CO': 'LLY',
  'EMBASSY OFFICE PARKS REIT': 'EMBASSY.NS',
  'ENGIE SA': 'ENGIY',
  'EOG Resources Inc': 'EOG',
  'EPIROC AB': 'EPOKY',
  'EQUINIX REIT INC': 'EQIX',
  'EQUINOX GOLD CORP': 'EQX',
  'EQUITY LIFESTYLE PPTY\'S INC': 'ELS',
  'EQUITY RESIDENTIAL REIT': 'EQR',
  'ERICSSON': 'ERIC',
  'ESSILORLUXOTTICA': 'ESLOY',
  'EURO-Bobl FUTURE MAR26 OEH6': 'BOND',
  'EVOLUTION MINING LTD': 'EVN.AX',
  'East West Bancorp': 'EWBC',
  'Eaton': 'ETN',
  'Eli Lilly & Co': 'LLY',
  'Eli Lilly & Co.': 'LLY',
  'Elite Material': '2383.TW',
  'Embassy Office Parks REIT': 'EMBASSY.NS',
  'Enel SpA': 'ENLAY',
  'Entergy Corp': 'ETR',
  'Equinor ASA': 'EQNR',
  'Etablissements Franz Colruyt NV': 'CLTEY',
  'Eurobank SA': 'EGFEY',
  'Exxon Mobil': 'XOM',
  'Exxon Mobil Corp': 'XOM',
  'FAST RETAILING': '9983.T',
  'FIRST SOLAR INC': 'FSLR',
  'FLEX LTD': 'FLEX',
  'FMC Corp (Fertilizers & Agricultural Chemicals)': 'FMC',
  'FORMOSA PLASTICS CORP': '1301.TW',
  'FORTIS HEALTHCARE INDIA LTD': 'FORTIS.NS',
  'FRESENIUS MEDICAL CARE AG & CO. KGAA': 'FMS',
  'FUJIBO HOLDINGS INC': '3104.T',
  'Fidelity National Info': 'FIS',
  'Fidelity National Information Services': 'FIS',
  'FormFactor': 'FORM',
  'Frasers Centrepoint Trust': 'J69U.SI',
  'Futu Holdings': 'FUTU',
  'GARTNER INC': 'IT',
  'GAZPROM': 'UNKNOWN',
  'GENTEIRA SAB DE CV': 'UNKNOWN',
  'GHK PLC': 'GSK',
  'GOODMAN GROUP UNITS': 'GMG.AX',
  'GRUPO AEROPORTUARIO DEL SURESTE SAB DE CV': 'ASR',
  'GRUPO MEXICO SAB DE CV': 'GMEXICOB.MX',
  'GSK': 'GSK',
  'GSK PLC': 'GSK',
  'Gilead Sciences, Inc.': 'GILD',
  'Glaxosmithkline plc': 'GSK',
  'Goldman Sachs': 'GS',
  'Greenko Wind Projects Maurit 7.25% 27/09/2028': 'UNKNOWN',
  'Grupo Financiero Banorte SAB de CV': 'GFNORTEO.MX',
  'HCA Healthcare': 'HCA',
  'HCL TECHNOLOGIES LTD': 'HCLTECH.NS',
  'HD HYUNDAI ELECTRIC CO LTD': '267260.KS',
  'HDFC BANK LTD': 'HDB',
  'HDFC Bank': 'HDB',
  'HEALTHPEAK PROPERTIES': 'DOC',
  'HINDALCO INDUSTRIES LTD': 'HINDALCO.NS',
  'HITACHI LTD (日本)': '6501.T',
  'HKT TRUST AND HKT LTD': '6823.HK',
  'HOYA': '7741.T',
  'HSBC': '0005.HK',
  'HSBC Holdings': '0005.HK',
  'HSBC Holdings Plc': '0005.HK',
  'HYUNDAI MOTOR CO': '005380.KS',
  'Halliburton Co': 'HAL',
  'Henkel AG & Co KGaA': 'HENKY',
  'Hitachi Ltd': '6501.T',
  'Hong Kong Exchanges & Clearing': '0388.HK',
  'Hong Kong Exchanges & Clearing Ltd': '0388.HK',
  'Hong Kong Exchanges & Clearing Ltd.': '0388.HK',
  'Hoya Corp': '7741.T',
  'Hyundai Motor Co': '005380.KS',
  'IAMGOLD CORP': 'IAG',
  'IBERDROLA SA': 'IBDRY',
  'ICELANDS SEAFOOD': 'UNKNOWN',
  'ICICI BANK LTD': 'IBN',
  'ICICI Bank': 'IBN',
  'ICICI Bank Ltd.': 'IBN',
  'ICU Medical Inc': 'ICUI',
  'IG集团': 'IGG.L',
  'INDUSTRIA DE DISENO TXTL IN SA': 'IDEXY',
  'INFINEON TECHNOLOGIES AG': 'IFNNY',
  'INFOSYS LTD': 'INFY',
  'ING GROEP NV': 'ING',
  'ING Groep NV': 'ING',
  'INTER &CO INC': 'INTR',
  'INTERNATIONAL FLAVS & FRAG INC': 'IFF',
  'INVERCO US TRS BD 1-3 YR ETF USD ACC': 'ETF',
  'INVESCO US TRS BD 1-3 YR ETF USD ACC': 'ETF',
  'INVITATION HOMES INC': 'INVH',
  'IRB Infrastructure Developer 7.11% 11/03/2032': 'IRB.NS',
  'IRON MOUNTAIN INC': 'IRM',
  'ISHARES $ FLOATING RATE BD UCITS ETF USD': 'ETF',
  'ISHARES $ SHT DURATION HY CRP BD UCITS E': 'ETF',
  'ISHARES $ ULTRASHORT BOND UCITS ETF USD': 'ETF',
  'ISHARES CORE MSCI EUROPE UCITS ETF': 'ETF',
  'ISHARES CORE S&P 500 UCITS ETF USD': 'ETF',
  'ISHARES CORP BD 0-3YR ESG SRI ETF ACC': 'ETF',
  'ISHARES MSCI EMERGING MARKETS ASIA ETF 4.9% 通訊服務': 'ETF',
  'ISHARES MSCI EMERGING MARKETS ASIA ETF 4.9% 通讯服务': 'ETF',
  'ISHARES MSCI EMERGING MARKETS UCIT': 'ETF',
  'ISHARES MSCI JAPAN UCITS ETF (': 'ETF',
  'ISHARES MSCI USA UCITS ETF USD ACC': 'ETF',
  'ISHARES PHYSICAL GOLD ETC PLC ETF-C': 'ETF',
  'ISHARES S&P 500 SWAP UCITS ETF USD': 'ETF',
  'ISUPTASYS CO LTD': 'UNKNOWN',
  'ITOCHU Corp': '8001.T',
  'ITT INC': 'ITT',
  'Iberdrola': 'IBDRY',
  'Iberdrola SA': 'IBDRY',
  'Infosys Ltd.': 'INFY',
  'Intesa Sanpaolo SpA': 'ISNPY',
  'Intuitive Surgical, Inc.': 'ISRG',
  'Invesco Funds-Invesco Asian Equity Fund': 'FUND',
  'Invesco Physical Gold Etc': 'ETF',
  'Itau Unibanco Holding SA': 'ITUB',
  'JD.COM': '9618.HK',
  'JD.COM INC': '9618.HK',
  'JPMORGAN CHASE & CO': 'JPM',
  'JPMorgan Chase & Co.': 'JPM',
  'JSW钢铁有限公司 5.05% 05/04/2032': 'JSTL.NS',
  'Johnson & Johnson': 'JNJ',
  'Johnson Controls International plc': 'JCI',
  'KB FINANCIAL GROUP INC': 'KB',
  'KB Financial Group, Inc.': 'KB',
  'KBC BANK NV (NEW YORK BRANCH)': 'KBC.BR',
  'KBC GROEP NV': 'KBCSY',
  'KDDI Corp': '9433.T',
  'KEYSIGHT TECHNOLOGIES IN (美国)': 'KEYS',
  'KINGSPAN GROUP PLC': 'KRX.L',
  'KINROSS GOLD CORP': 'KGC',
  'KLABIN SA': 'KLBAY',
  'KONE OYJ': 'KNYJY',
  'KOTAK MAHINDRA BANK LTD': 'KOTAKBANK.NS',
  'Keppel DC REIT': 'AJBU.SI',
  'King Yuan Electronics': '2449.TW',
  'Kingboard Laminates Holdings Limited': '1888.HK',
  'Knorr-Bremse AG': 'KBX.DE',
  'Koninklijke Ahold Delhaize NV': 'ADRNY',
  'Koninklijke Ahold Delhaize NV (Food Retail)': 'ADRNY',
  'Kubota Corp (Agricultural & Farm Machinery)': '6326.T',
  'L3HARRIS TECHNOLOGIES INC': 'LHX',
  'LAM RESEARCH CORP': 'LRCX',
  'LEGRAND SA': 'LGRVF',
  'LLOYDS BANKING GROUP PLC': 'LYG',
  'LOCALIZA RENT A CAR SA': 'LCNVF',
  'LOTTE CHEMICAL CORP': '011170.KS',
  'LYNAS RARE EARTH LTD': 'LYC.AX',
  'Latam Airlines Group SA': 'LTM',
  'Leer Corp': 'LCI',
  'Link Real Estate Investment Trust': '0823.HK',
  'Lite-On Technology': '2301.TW',
  'Littelfuse Inc': 'LFUS',
  'Loews': 'L',
  'MAGNITOGORSKIY METALLURGICHESKIY K': 'UNKNOWN',
  'MASTERCARD INC A': 'MA',
  'MBONO 7.5% 05/33 M': 'BOND',
  'MCKESSON CORP': 'MCK',
  'MEDIATEK INC': '2454.TW',
  'MEDTRONIC PLC': 'MDT',
  'MERCADOLIBRE INC': 'MELI',
  'META PLATFORMS INC': 'META',
  'META PLATFORMS INC CLASS A': 'META',
  'META PLATFORMS INC-CLASS A': 'META',
  'MICRON TECHNOLOGY INC': 'MU',
  'MICROSOFT CORP': 'MSFT',
  'MITSUI FUDOSAN CO LTD': '8801.T',
  'MITSUI FUDOSAN LTD': '8801.T',
  'MONOLITHIC POWER SYSTEMS INC (美国)': 'MPWR',
  'MORGAN STANLEY': 'MS',
  'MORGAN STANLEY INVESTMENT FUNDS - EMERGING MARKETS CORPORATE DEBT FUND': 'FUND',
  'MTU航空发动机': 'MTX.DE',
  'MUENCHENER RUECKVERSICHERUNGS-GESELLSCHAFT AG IN MUENCHEN': 'MUV2.DE',
  'Mapletree Industrial Trust': 'ME8U.SI',
  'Mapletree Logistics Trust': 'M44U.SI',
  'Mapletree Pan Asia Commercial Trust': 'N2IU.SI',
  'Marks & Spencer Group PLC': 'MAKSY',
  'Marvell Technology Inc.': 'MRVL',
  'McDonald\'s': 'MCD',
  'McDonald\'s Corp (Restaurants)': 'MCD',
  'McDonalds': 'MCD',
  'McKesson Corp.': 'MCK',
  'MediaTek': '2454.TW',
  'Medtronic PLC': 'MDT',
  'Meituan': '3690.HK',
  'Meituan (Restaurants)': '3690.HK',
  'Meta Platforms': 'META',
  'Meta Platforms \'A\'': 'META',
  'Meta Platforms, Inc.': 'META',
  'Meta(脸书母公司)': 'META',
  'Meta平台股份有限公司': 'META',
  'Microsoft': 'MSFT',
  'Microsoft Corp': 'MSFT',
  'Microsoft Corp.': 'MSFT',
  'Midea Group': '000333.SZ',
  'Mitsubishi Electric Corp': '6503.T',
  'Mitsubishi UFJ Financial Group Inc': '8306.T',
  'Morgan Stanley': 'MS',
  'Mowi ASA (Packaged Foods & Meat)': 'MHGVY',
  'NATIONAL AUSTRALIA BANK LTD': 'NAB.AX',
  'NATIONAL GRID PLC': 'NGG',
  'NETEASE INC': 'NTES',
  'NEWMONT CORP': 'NEM',
  'NEXGEN ENERGY LTD': 'NXE',
  'NEXTPOWER INC': 'UNKNOWN',
  'NEXTPOWER INC CL A': 'UNKNOWN',
  'NINETY ONE GSF - EMERGING MARKETS LOCAL CURRENCY DYNAMIC DEBT FUND': 'FUND',
  'NK LUKOIL': 'UNKNOWN',
  'NK ROSNEFT': 'UNKNOWN',
  'NORDEA BANK ABP (NEW YORK BRANCH)': 'NRDBY',
  'NOVABEV GROUP': 'UNKNOWN',
  'NOVARTIS AG': 'NVS',
  'NOVATEK': 'UNKNOWN',
  'NOVOLIPETSK STEEL': 'UNKNOWN',
  'NOW Inc': 'DNOW',
  'NU HOLDINGS LTD': 'NU',
  'NU HOLDINGS LTD/CAYMAN ISLANDS': 'NU',
  'NVIDIA CORP': 'NVDA',
  'NVIDIA Corp': 'NVDA',
  'NVIDIA Corp.': 'NVDA',
  'NVIDIACorp.': 'NVDA',
  'NatWest Group PLC': 'NWG.L',
  'Nebius': 'NBIS',
  'Nestle': 'NSRGY',
  'Nestle SA': 'NSRGY',
  'Nestle SA (Packaged Foods & Meat)': 'NSRGY',
  'NetEase': 'NTES',
  'NetEase Inc': 'NTES',
  'Netflix, Inc.': 'NFLX',
  'NextEra Energy, Inc.': 'NEE',
  'Nintendo': '7974.T',
  'Novartis': 'NVS',
  'Novartis AG': 'NVS',
  'Novo Nordisk': 'NVO',
  'Novo Nordisk A/S': 'NVO',
  'Nu Holdings': 'NU',
  'Nutrien Ltd (Fertilizers & Agricultural Chemicals)': 'NTR',
  'Nvidia': 'NVDA',
  'Nvidia Corp': 'NVDA',
  'OESTEREICH KONTROLLBANK': 'UNKNOWN',
  'OMERS FINANCE TRUST': 'UNKNOWN',
  'ONEVIEW HEALTHCARE PLC': 'ONE.AX',
  'ONVIEW HEALTHCARE PLC': 'UNKNOWN',
  'OPEN TEXT CORP': 'OTEX',
  'ORACLE CORP': 'ORCL',
  'ORIX Corp': '8591.T',
  'ORLEN SA': 'PKN.WA',
  'OTP BANK NYRT': 'OTPBY',
  'OTP银行': 'OTPBY',
  'Option Care Health Inc': 'OPCH',
  'Oracle': 'ORCL',
  'Orange SA': 'ORAN',
  'Orion Group Holdings Inc': 'ORN',
  'Oversea-Chinese Banking': 'O39.SI',
  'Ovintiv Inc': 'OVV',
  'PACIFIC BASIN SHIPPING LTD': '2343.HK',
  'PAN AMERICAN SILVER CORP': 'PAAS',
  'PDD HOLDINGS INC': 'PDD',
  'PDD Holdings': 'PDD',
  'PETROLEO BRASILEIRO-PETROBRAS': 'PBR',
  'PING AN INSURANCE GROUP CO OF CHINA LTD': '2318.HK',
  'PPL Corporation': 'PPL',
  'PRINCIPAL GI FIN UNCON EM FX INC I2 ACC': 'FUND',
  'PRYSMIAN SPA': 'PRYMY',
  'PT T POL': 'UNKNOWN',
  'PUBLIC STORAGE': 'PSA',
  'PUBLIC STORAGE REIT': 'PSA',
  'Panasonic Holdings Corp': '6752.T',
  'PetroChina Co Ltd': 'PTR',
  'Pfizer Inc': 'PFE',
  'Ping An Insurance (Group) Company of China, Ltd.': '2318.HK',
  'Ping An Insurance Group': '2318.HK',
  'Piramal Finance 7.80% 29/01/2028': 'PEL.NS',
  'Power Grid Corporation of India Ltd.': 'POWERGRID.NS',
  'Prysmian SpA': 'PRYMY',
  'RECKITT BENCKISER GROUP PLC': 'RBGLY',
  'REGIONAL SAB DE CV': 'RA.MX',
  'RELIANCE INDUSTRIES LTD': 'RELIANCE.NS',
  'RENTOKIL INITIAL PLC': 'RTO.L',
  'ROCHE HOLDING AG': 'RHHBY',
  'ROCKWELL AUTOMATION INC': 'ROK',
  'ROLLS-ROYCE HOLDINGS PLC': 'RR.L',
  'ROLODIS INC': 'PLD',
  'ROLOGIS INC': 'PLD',
  'Repligen Corp': 'RGEN',
  'Repsol SA': 'REPYY',
  'Resideo Technologies Inc': 'REZI',
  'Rio Tinto Ltd.': 'RIO',
  'Rio Tinto PLC': 'RIO',
  'Robinhood Markets': 'HOOD',
  'Robinhood Markets Inc': 'HOOD',
  'Roche': 'RHHBY',
  'Roche Holding AG': 'RHHBY',
  'Rolls-Royce': 'RR.L',
  'SAMSUNG C&T CORP': '028260.KS',
  'SAMSUNG ELECTRO-MECHANICS CO LTD': '009150.KS',
  'SAMSUNG ELECTRONICS CO LTD': '005930.KS',
  'SAMSUNG ELECTRONICS GDS REPRESENT': '005930.KS',
  'SAMSUNG ELECTRONICS LTD': '005930.KS',
  'SANDISK CORP': 'SNDK',
  'SANEAMENTO BASICO DE SP (CIA)': 'SBS',
  'SAP SE': 'SAP',
  'SBERBANK ROSSI': 'UNKNOWN',
  'SEZZLE INC': 'SZL.AX',
  'SHOALS TECHNOLOGIES GROUP A': 'SHLS',
  'SIEMENS AG': 'SIEGY',
  'SIEMENS ENERGY AG': 'SMNEY',
  'SIGB 2.625% 08/32': 'BOND',
  'SINGAPORE TELECOMMUNICATIONS LTD': 'SINGTEL.SI',
  'SK HYNIX INC': '000660.KS',
  'SK Hynix, Inc.': '000660.KS',
  'SK INNOVATION CO LTD': '096770.KS',
  'SK SQUARE CO LTD': '402340.KS',
  'SK SQUARE LTD': '402340.KS',
  'SK hynix': '000660.KS',
  'SK hynix, Inc.': '000660.KS',
  'SK海力士': '000660.KS',
  'SLB Ltd': 'SLB',
  'SOUTHERN COPPER CORP': 'SCCO',
  'SPAIN 3.45% 10/34': 'BOND',
  'SSE plc': 'SSE.L',
  'STANDARD CHARTERED BANK (NEW YORK': 'STAN.L',
  'SUNCOR ENERGY INC (CANADA)': 'SU',
  'SUNRUN INC': 'RUN',
  'Sa su ng le ctr on ic Co td': '005930.KS',
  'Sammaan Capital 7.50% 16/10/2030': 'IIFL.NS',
  'Samsung Electronics': '005930.KS',
  'Sanofi': 'SNY',
  'Sanofi SA': 'SNY',
  'Sea ADR': 'SE',
  'Select Water Solutions Inc': 'WTTR',
  'Severn Trent Plc': 'SVT.L',
  'Shell': 'SHEL',
  'Shell PLC': 'SHEL',
  'Shopify \'A\'': 'SHOP',
  'Shriram Finance Ltd. 6.15% 03/04/2028': 'SHRIRAMFIN.NS',
  'Siemens AG': 'SIEGY',
  'Simpson Manufacturing Co Inc': 'SSD',
  'Sk Hynix Inc': '000660.KS',
  'Snowflake': 'SNOW',
  'Societe Generale SA': 'SCGLY',
  'Sony Group': '6758.T',
  'Sony Group Corp': '6758.T',
  'Standard Chartered': 'STAN.L',
  'Stanley Black & Decker Inc': 'SWK',
  'State Bank of India': 'SBIN.NS',
  'Stryker Corp.': 'SYK',
  'Studio城市金融有限公司 5.00% 15/01/2029': '0027.HK',
  'Sumitomo Mitsui Trust Group Inc': '8309.T',
  'Sumitomo Realty & Development Co Ltd': '8830.T',
  'Sungrow Power Supply': '300274.SZ',
  'Suntec Real Estate Investment Trust': 'T82U.SI',
  'Suzuki Motor Corp': '7269.T',
  'Swatch Group AG/The': 'SWGAY',
  'Swiss Re AG': 'SSREY',
  'T-MOBILE USA INC': 'TMUS',
  'TAIWAN SEMICOND MANUFG -TSMC': 'TSM',
  'TAIWAN SEMICONDUCTOR MANUFACTURING CO LTD': 'TSM',
  'TAIWAN SEMICONDUCTOR MFG CO LTD': 'TSM',
  'TAIWAN SEMICONDUCTOR-SP ADR': 'TSM',
  'TATNEFT': 'UNKNOWN',
  'TATNEFT PREF': 'UNKNOWN',
  'TAWAN SEMICONDUCTOR-SP ADR': 'TSM',
  'TC ENERGY CORP': 'TRP',
  'TC Energy Corp.': 'TRP',
  'TE Connectivity PLC': 'TEL',
  'TECHTRONIC INDUSTRIES CO LTD': '0669.HK',
  'TELEDYNE TECHNOLOGIES INC': 'TDY',
  'TELKOM INDONESIA PERSERO TBK PT': 'TLK',
  'TENCENT HLDGS LTD': '0700.HK',
  'TENCENT HOLDINGS LTD': '0700.HK',
  'TERNA RETE ELETTRICA NAZIONALE': 'TRN.MI',
  'TESLA INC': 'TSLA',
  'TETRA TECHNOLOGIES INC COMMON': 'TTI',
  'TEXAS INSTRUMENTS INC': 'TXN',
  'TJX Cos Inc/The': 'TJX',
  'TORONTO-DOMINION BANK (NEW YORK BR': 'TD',
  'TOTALENERGIES SE': 'TTE',
  'TOYO TANSO CO LTD': '5310.T',
  'TRI-PARTY BOFA SECURITIES INC.': 'BOND',
  'TRI-PARTY TD SECURITIES (USA) LLC': 'BOND',
  'TSMC': 'TSM',
  'Taiwan Semiconductor': 'TSM',
  'Taiwan Semiconductor Manufac': 'TSM',
  'Taiwan Semiconductor Manufacturing': 'TSM',
  'Taiwan Semiconductor Manufacturing Company': 'TSM',
  'Take-Two Interactive Software': 'TTWO',
  'Takeaway.com NV (Internet Retail)': 'TKWY.AS',
  'Teletra Group': 'UNKNOWN',
  'Telstra Group': 'TLS.AX',
  'Tencent': '0700.HK',
  'Tencent Holdings': '0700.HK',
  'Tencent Holdings Ltd': '0700.HK',
  'Tencent Holdings Ltd.': '0700.HK',
  'Tesla': 'TSLA',
  'Tesla Inc': 'TSLA',
  'Teva Pharmaceutical Industries Ltd': 'TEVA',
  'Texas Instruments': 'TXN',
  'Thermo Fisher Scientific Inc': 'TMO',
  'Tokio Marine Holdings Inc': '8766.T',
  'TotalEnergies': 'TTE',
  'Trip.com Group': 'TCOM',
  'Trip.com Group Ltd': 'TCOM',
  'Trip.com Group Ltd.': 'TCOM',
  'Tyson Foods Inc (Packaged Foods & Meat)': 'TSN',
  'UK TSY 4.125% 07/29': 'BOND',
  'UNICREDIT SPA': 'UNCRY',
  'UNILEVER PLC': 'UL',
  'UNIMICRON TECHNOLOGY CORP': '3037.TW',
  'UNION PACIFIC CORP': 'UNP',
  'UNITED KINGDOM': 'BOND',
  'UNITIE GROUP PLC': 'UTG.L',
  'UPL LTD': 'UPL.NS',
  'US TSY 1.125% 05/40': 'BOND',
  'US TSY 2.375% 02/42': 'BOND',
  'US TSY 2.75% 08/32': 'BOND',
  'US TSY 2.875% 08/28': 'BOND',
  'US TSY 3.5% 01/30': 'BOND',
  'US TSY 3.875% 08/34': 'BOND',
  'US TSY 4.125% 08/44': 'BOND',
  'US TSY 4.125% 11/29': 'BOND',
  'US TSY 4.125% 11/32': 'BOND',
  'US TSY 4.25% 08/35': 'BOND',
  'US TSY 5% 5/37': 'BOND',
  'Uni-President Enterprises Corp.': '1216.TW',
  'Union Pacific Corp': 'UNP',
  'UnitedHealth Group Inc': 'UNH',
  'UnitedHealth Group, Inc.': 'UNH',
  'Us Treasury N/B 4% 31.01.2029 Uns': 'BOND',
  'Us Treasury N/B 4.125% 15.11.2032 Uns': 'BOND',
  'Us Treasury N/B 4.25% 31.12.2026 Uns': 'BOND',
  'VALE SA': 'VALE',
  'VANGUARD S&P 500 ETF 8.6% 能源相關': 'ETF',
  'VANGUARD S&P 500 ETF 8.6% 能源相关': 'ETF',
  'VANGUARD USD CORPO 1-3 YEAR BD UCITS ETF': 'ETF',
  'VERTIV HOLDINGS CO A': 'VRT',
  'VINCI SA': 'VCISY',
  'VISA INC': 'V',
  'VONOVA SE': 'VNA.DE',
  'Valmont Industries Inc': 'VMI',
  'Veritiv Holdings Co': 'VRTV',
  'Verizon Communications Inc': 'VZ',
  'Vertex Pharmaceuticals Inc': 'VRTX',
  'Visa, Inc.': 'V',
  'Vodafone Group PLC': 'VOD',
  'WELLS FARGO & CO': 'WFC',
  'WELLS FARGO & CO NEW': 'WFC',
  'WELLTOWER INC': 'WELL',
  'WEX INC': 'WEX',
  'WIWYNN CORPORATION CORP': '6669.TW',
  'WONIK MATERIALS CO LTD': '104830.KS',
  'WSP GLOBAL INC': 'WSP.TO',
  'Walt Disney': 'DIS',
  'Waste Management Inc (Environmental & Facilities Services)': 'WM',
  'Wells Fargo': 'WFC',
  'West Pharmaceutical Services Inc': 'WST',
  'Wheaton Precious Metals': 'WPM',
  'Williams Cos Inc': 'WMB',
  'Wiwynn Corporation': '6669.TW',
  'XIAOMI CORP': '1810.HK',
  'Xiaomi': '1810.HK',
  'Xiaomi Corporation': '1810.HK',
  'ZUIN MINING GROUP CO LTD': '2899.HK',
  'Zhongji Innolight': '300308.SZ',
  'Zhongji Innolight Co., Ltd.': '300308.SZ',
  'INNOLIGHT': '300308.SZ',
  '中际旭创': '300308.SZ',
  '中際旭創': '300308.SZ',
  'Zijin Mining Group': '2899.HK',
  'Zijin Mining Group Co Ltd': '2899.HK',
  '万事达': 'MA',
  '万喜': 'VCISY',
  '三一重工': '600031.SS',
  '三星电子': '005930.KS',
  '上海实业环境控股有限公司': '0807.HK',
  '中国光大环境集团有限公司': '0807.HK',
  '中国宏桥集团': '1378.HK',
  '中国平安保险': '2318.HK',
  '中国建筑国际集团有限公司': '3311.HK',
  '中国建设银行': '0939.HK',
  '中国建设银行股份有限公司': '0939.HK',
  '中国电信股份有限公司': '0728.HK',
  '中国移动有限公司': '0941.HK',
  '中国工商银行股份有限公司－H': '1398.HK',
  '中国建设银行股份有限公司－H': '0939.HK',
  '中国移动有限公司－H': '0941.HK',
  '中银保诚日本中小企业机遇基金': 'FUND',
  '中國工商銀行股份有限公司－H': '1398.HK',
  '中國建設銀行股份有限公司－H': '0939.HK',
  '中國移動有限公司－H': '0941.HK',
  '中銀保誠日本中小企業機遇基金': 'FUND',
  '乐购': 'TSCO.L',
  '亚马逊': 'AMZN',
  '亚马逊公司': 'AMZN',
  '伊克赛尔服务': 'UNKNOWN',
  '伊格尔矿业': 'EGO',
  '伊比德罗拉': 'IBDRY',
  '优步': 'UBER',
  '伟尔集团': 'WEIR.L',
  '借贷俱乐部': 'LC',
  '公民金融集团': 'CFG',
  '其他': 'UNKNOWN',
  '凯克萨银行': 'UNKNOWN',
  '力拓集团': 'RIO',
  '加拿大自然资源': 'CNQ',
  '北方之星资源': 'NST.AX',
  '北方银行': 'UNKNOWN',
  '博格华纳公司': 'BWA',
  '博通': 'AVGO',
  '印地纺': 'IDEXY',
  '历峰集团': 'CFR.SW',
  '原材料 公用 2.1%': 'UNKNOWN',
  '友邦保险控股有限公司': '1299.HK',
  '友邦保險控股有限公司': '1299.HK', // 旧库繁体持仓名，与上同义
  '台光电子材料股份有限公司': '2383.TW',
  '台湾积体电路制造股份有限公司': 'TSM',
  '台积电': 'TSM',
  '吉利德科学': 'GILD',
  '嘉信理财集团': 'SCHW',
  '嘉能可': 'GLNCY',
  '埃克森美孚': 'XOM',
  '埃尔拉多黄金': 'EGO',
  '壳牌': 'SHEL',
  '大豆': 'COMMODITY',
  '天然气': 'COMMODITY',
  '奋进矿业': 'EDV.TO',
  '奥驰亚': 'MO',
  '威廉姆斯公司': 'WMB',
  '威瑞森通信': 'VZ',
  '宁德时代': '300750.SZ',
  '宁德时代新能源科技股份': '300750.SZ',
  '安格鲁阿散蒂黄金有限公司': 'AU',
  '小米集团－B类别': '1810.HK',
  '小米集團－B類別': '1810.HK',
  '巴克莱银行': 'BCS',
  '巴西石油': 'PBR',
  '巴里克黄金公司': 'GOLD',
  '布伦特原油': 'COMMODITY',
  '平安保险': '2318.HK',
  '康菲石油': 'COP',
  '开市客': 'COST',
  '强生公司': 'JNJ',
  '微软': 'MSFT',
  '德意志银行': 'DB',
  '恩智浦半导体': 'NXPI',
  '惠顿贵金属': 'WPM',
  '意大利联合圣保罗银行': 'ISNPY',
  '招商银行股份有限公司': '3968.HK',
  '携程': 'TCOM',
  '摩根大通': 'JPM',
  '新纪元能源': 'UNKNOWN',
  '施耐德电气': 'SBGSY',
  '易昆尼克斯': 'EQIX',
  '普洛斯公司': 'GLP',
  '普睿司曼': 'PRYMY',
  '智利矿业化工': 'SQM',
  '林德集团': 'LIN',
  '柯蒂斯·莱特': 'CW',
  '沃尔玛': 'WMT',
  '沃尔玛墨西哥与中美洲': 'WALMEX.MX',
  '法国兴业银行': 'SCGLY',
  '泛林集团': 'LRCX',
  '泛美白银公司': 'PAAS',
  '波多黎各大众银行': 'BPOP',
  '泰科电子': 'TEL',
  '洛阳钼业': '3993.HK',
  '活畜': 'COMMODITY',
  '淡水河谷': 'VALE',
  '汇丰控股有限公司 9.0% 通讯服务': '0005.HK',
  '滙豐控股有限公司 9.0% 通訊服務': '0005.HK',
  '爱尔兰联合银行': 'AIB.IR',
  '爱德万测试': '6857.T',
  '玉米': 'COMMODITY',
  '环汇': 'UNKNOWN',
  '瑞银集团': 'UBS',
  '百度': 'BIDU',
  '皇冠控股': 'CCL.AX',
  '礼来': 'LLY',
  '第一太阳能': 'FSLR',
  '第一资本': 'COF',
  '紫金矿业集团股份有限公司': '2899.HK',
  '纽蒙特黄金': 'NEM',
  '纽蒙特黄金公司': 'NEM',
  '维斯塔斯风力系统公司': 'VWDRY',
  '维萨卡': 'V',
  '网易': 'NTES',
  '罗氏': 'RHHBY',
  '罗氏大药厂': 'RHHBY',
  '美光科技': 'MU',
  '美团': '3690.HK',
  '美国洲际交易所': 'ICE',
  '美国金德摩根公司': 'KMI',
  '美国银行': 'BAC',
  '美团－B类别': '3690.HK',
  '美團－B類別': '3690.HK',
  '美敦力': 'MDT',
  '联发科技': '2454.TW',
  '联合健康': 'UNH',
  '腾讯': '0700.HK',
  '腾讯控股有限公司': '0700.HK',
  '艾伯维': 'ABBV',
  '芝加哥商品交易所': 'CME',
  '花旗集团': 'C',
  '苏格兰南方能源公司': 'SSE.L',
  '英伟达': 'NVDA',
  '英国国家电力供应公司': 'NGG',
  '苹果': 'AAPL',
  '苹果公司': 'AAPL',
  '菲律宾国际债券 4.50% 14/07/2028': 'BOND',
  '裕信银行': 'UNCRY',
  '西得克萨斯中间基原油': 'COMMODITY',
  '西蒙地产集团': 'SPG',
  '西门子': 'SIEGY',
  '诺华': 'NVS',
  '费利浦·麦克莫兰铜金公司': 'FCX',
  '赛峰集团': 'SAF.PA',
  '达能': 'DANOY',
  '远东宏信有限公司': '3360.HK',
  '通用汽车': 'GM',
  '道达尔': 'TTE',
  '野村房地产': '3231.T',
  '金田有限公司': 'UNKNOWN',
  '金罗斯黄金': 'KGC',
  '金罗斯黄金公司': 'KGC',
  '铁山公司': 'IRM',
  '铜': 'COMMODITY',
  '铝': 'COMMODITY',
  '银': 'COMMODITY',
  '镍业有限公司 9.00% 30/09/2030': 'UNKNOWN',
  '阿拉莫斯黄金': 'AGI',
  '阿斯利康': 'AZN',
  '阿斯麦': 'ASML',
  '阿斯麦控股公司': 'ASML',
  '阿里巴巴': 'BABA',
  '阿里巴巴集团': 'BABA',
  '阿里巴巴集团控股有限公司': 'BABA',
  '阿里巴巴集團控股有限公司': 'BABA',
  '雪佛龙': 'CVX',
  '香港交易及结算所有限公司': '0388.HK',
  '香港交易及結算所有限公司': '0388.HK',
  '香港电讯信托与香港电讯': '6823.HK',
  '騰訊控股有限公司': '0700.HK', // 旧库繁体；规范名见「腾讯控股有限公司」
  '马恒达公司': 'M&M.NS',
  '黄金': 'COMMODITY',
  '默克': 'MRK',
}

export const US_STOCK_TICKERS = new Set([
  '000333.SZ', '300274.SZ', '300308.SZ', '300750.SZ', '600031.SS', 'AA', 'AAPL', 'ABB',
  'ABBV', 'ACN', 'ADC', 'ADI', 'ADRNY', 'ADSK', 'AEM', 'AENA.MC',
  'AEP', 'AER', 'AGCO', 'AGI', 'AIBG', 'ALIZY', 'AMAT', 'AMD',
  'AMH', 'AMZN', 'APH', 'APP', 'ARE', 'ARES', 'ASML', 'ASR',
  'ATRO', 'AU', 'AVGO', 'AXAHY', 'AXP', 'AZN', 'BABA', 'BAC',
  'BBD', 'BCPC', 'BCS', 'BDORY', 'BEP', 'BFAM', 'BG', 'BHP',
  'BIDU', 'BKR', 'BKU', 'BMY', 'BNPQY', 'BP', 'BPOP', 'BRK-B',
  'BSX', 'BWA', 'C', 'CAH', 'CAIXY', 'CARR', 'CAT', 'CCEP',
  'CCJ', 'CECO', 'CF', 'CFG', 'CIEN', 'CLTEY', 'CME', 'CMS',
  'CNP', 'CNQ', 'COF', 'COHR', 'COP', 'COST', 'CP', 'CPT',
  'CRDO', 'CRRFY', 'CRWD', 'CRWV', 'CRZBY', 'CTRA', 'CTRE', 'CTSH',
  'CTTAY', 'CTVA', 'CVCO', 'CVX', 'CW', 'DANOY', 'DASH', 'DB',
  'DBOEY', 'DCI', 'DE', 'DIS', 'DLR', 'DNOW', 'DOC', 'DPSGY',
  'DTEGY', 'EADSY', 'EDRVF', 'EGFEY', 'EGO', 'ELS', 'ELV', 'ENGIY',
  'ENLAY', 'EOG', 'EONGY', 'EPOKY', 'EQIX', 'EQNR', 'EQR', 'EQX',
  'ERIC', 'ESLOY', 'ETN', 'ETR', 'EWBC', 'FCX', 'FIS', 'FLEX',
  'FMC', 'FMS', 'FORM', 'FSLR', 'FUTU', 'GILD', 'GLNCY', 'GLP',
  'GLW', 'GM', 'GOLD', 'GOOG', 'GOOGL', 'GS', 'GSK', 'HAL',
  'HCA', 'HDB', 'HENKY', 'HOOD', 'IAG', 'IBDRY', 'IBN', 'ICE',
  'ICUI', 'IDEXY', 'IFF', 'IFNNY', 'INFY', 'ING', 'INTR', 'INVH',
  'IRM', 'ISNPY', 'ISRG', 'IT', 'ITT', 'ITUB', 'JCI', 'JNJ',
  'JPM', 'KB', 'KBCSY', 'KEYS', 'KGC', 'KLBAY', 'KMI', 'KNYJY',
  'KO', 'L', 'LC', 'LCI', 'LCNVF', 'LFUS', 'LGRVF', 'LHX',
  'LIN', 'LLY', 'LNG', 'LRCX', 'LTM', 'LYG', 'MA', 'MAKSY',
  'MCD', 'MCK', 'MDT', 'MELI', 'META', 'MHGVY', 'MO', 'MPWR',
  'MRK', 'MRVL', 'MS', 'MSFT', 'MU', 'NBIS', 'NEE', 'NEM',
  'NFLX', 'NGG', 'NGLOY', 'NRDBY', 'NSRGY', 'NTES', 'NTR', 'NU',
  'NVDA', 'NVO', 'NVS', 'NXE', 'NXPI', 'OPCH', 'ORAN', 'ORCL',
  'ORN', 'OTEX', 'OTPBY', 'OVV', 'PAAS', 'PBR', 'PDD', 'PFE',
  'PLD', 'PPL', 'PRYMY', 'PSA', 'PTR', 'RBGLY', 'REPYY', 'REZI',
  'RGEN', 'RHHBY', 'RIO', 'ROK', 'RUN', 'SAN', 'SAP', 'SBGSY',
  'SBS', 'SCCO', 'SCGLY', 'SCHW', 'SE', 'SHEL', 'SHLS', 'SHOP',
  'SIEGY', 'SLB', 'SMNEY', 'SNDK', 'SNOW', 'SNY', 'SPG', 'SQ',
  'SQM', 'SSD', 'SSREY', 'SU', 'SWGAY', 'SWK', 'SYK', 'TCOM',
  'TD', 'TDY', 'TEL', 'TEVA', 'TJX', 'TLK', 'TMO', 'TMUS',
  'TRP', 'TSLA', 'TSM', 'TSN', 'TTE', 'TTI', 'TTWO', 'TXN',
  'UBER', 'UBS', 'UL', 'UNCRY', 'UNH', 'UNP', 'V', 'VALE',
  'VCISY', 'VMI', 'VOD', 'VRT', 'VRTV', 'VRTX', 'VWDRY', 'VZ',
  'WELL', 'WEX', 'WFC', 'WM', 'WMB', 'WMS', 'WMT', 'WPM',
  'WST', 'WTTR', 'XOM',
])

export function getTickerFromHolding(name: string): string | null {
  if (!name) return null
  const trimmed = name.trim()
  
  // Exact match
  const exact = HOLDING_TICKER_MAP[trimmed]
  if (exact) return exact
  
  // Try with quotes removed
  const noQuotes = trimmed.replace(/^[\"']|[\"']$/g, '')
  if (HOLDING_TICKER_MAP[noQuotes]) return HOLDING_TICKER_MAP[noQuotes]
  
  // Case-insensitive
  const upper = trimmed.toUpperCase()
  for (const [key, ticker] of Object.entries(HOLDING_TICKER_MAP)) {
    if (key.toUpperCase() === upper) return ticker
  }
  
  // Partial match (min 8 chars to avoid false positives)
  for (const [key, ticker] of Object.entries(HOLDING_TICKER_MAP)) {
    if (key.length >= 8 && trimmed.length >= 8) {
      if (upper.includes(key.toUpperCase()) || key.toUpperCase().includes(upper)) {
        return ticker
      }
    }
  }
  
  return null
}

export function isUSStock(ticker: string | null): boolean {
  if (!ticker) return false
  const t = String(ticker).trim().toUpperCase()
  // 只允许“纯美股 ticker”：不含 .HK/.TW/.KS/.T 等后缀，也不以数字开头
  if (!US_STOCK_TICKERS.has(t)) return false
  if (t.includes(".")) return false
  if (/^\d/.test(t)) return false
  return true
}

const NON_NAV_TICKERS = new Set(["BOND", "ETF", "COMMODITY", "FUND", "UNKNOWN"]);

export function isClickable(holdingName: string): boolean {
  const ticker = getTickerFromHolding(holdingName);
  if (!ticker || NON_NAV_TICKERS.has(ticker)) return false;
  if (isUSStock(ticker)) return true;
  if (isGlobalEquityTicker(ticker)) return true;
  return false;
}

